### PR TITLE
test: jestify new-contract-endpoint test

### PR DESCRIPTION
**Pull request by awadhana**
Migrated test from Tap to Jest.

File Path:
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/new-contract-endpoint.test.ts

This is a PARTIAL resolution to issue #238

Signed-off-by: awadhana <awadhana0825@gmail.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@awadhana LGTM but before merging please make sure the PR description and the git commit are updated to not resolve the main jest issue.

**Comment by awadhana** [comment]
> @awadhana LGTM but before merging please make sure the PR description and the git commit are updated to not resolve the main jest issue.

@petermetz Done :)

**Review by petermetz — CHANGES_REQUESTED** [review]
@awadhana I think the taprc/jest ignore/include patterns have gone sideways on this one too (don't see them in the diff at all) if you fix that probably the CI will start passing as well.

**Comment by awadhana** [comment]
> @awadhana I think the taprc/jest ignore/include patterns have gone sideways on this one too (don't see them in the diff at all) if you fix that probably the CI will start passing as well.

@petermetz done :)

**Review by petermetz — APPROVED** [review]
@awadhana Thank you very much, LGTM!

**Pull request merged**
