### PR TITLE
test: jestify test-plugin-htlc-eth-besu get-status-endpoint test

### PR DESCRIPTION
**Pull request by awadhana**
Migrated test from Tap to Jest.

File Path:
packages/cactus-test-plugin-htlc-eth-besu/
src/test/typescript/integration/
plugin-htlc-eth-besu/get-status-endpoint.test.ts

This is a PARTIAL resolution to issue #238

Signed-off-by: awadhana <awadhana0825@gmail.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — APPROVED** [review]
@awadhana LGTM, thank you very much!

**Comment by petermetz** [comment]
@awadhana Seems like something is not right with either .taprc or jest.config because it is failing on account of tap/tape trying to run a jestified test:

```sh
022-01-19T05:19:36.1684499Z Unable to find Jest's global expect.
2022-01-19T05:19:36.1686007Z Please check you have added jest-extended correctly to your jest configuration.
2022-01-19T05:19:36.1687570Z See https://github.com/jest-community/jest-extended#setup for help.
2022-01-19T05:19:47.1802580Z /home/runner/work/cactus/cactus/packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts:2
2022-01-19T05:19:47.1803883Z import type { AddressInfo } from "net";
2022-01-19T05:19:47.1807366Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ^
2022-01-19T05:19:47.1891725Z ReferenceError: describe is not defined
2022-01-19T05:19:47.1894274Z     at Object.<anonymous> (/home/runner/work/cactus/cactus/packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts:2:2159)
2022-01-19T05:19:47.1896065Z     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2022-01-19T05:19:47.1896992Z     at Module.replacementCompile (/home/runner/work/cactus/cactus/node_modules/append-transform/index.js:60:13)
2022-01-19T05:19:47.1897896Z     at Module.m._compile (/home/runner/work/cactus/cactus/node_modules/ts-node/src/index.ts:1311:23)
2022-01-19T05:19:47.1898766Z     at module.exports (/home/runner/work/cactus/cactus/node_modules/default-require-extensions/js.js:7:9)
2022-01-19T05:19:47.1899571Z     at /home/runner/work/cactus/cactus/node_modules/append-transform/index.js:64:4
2022-01-19T05:19:47.1900401Z     at require.extensions.<computed> (/home/runner/work/cactus/cactus/node_modules/ts-node/src/index.ts:1314:12)
2022-01-19T05:19:47.1901252Z     at Object.<anonymous> (/home/runner/work/cactus/cactus/node_modules/append-transform/index.js:64:4)
2022-01-19T05:19:47.1901842Z     at Module.load (internal/modules/cjs/loader.js:937:32)
2022-01-19T05:19:47.1902369Z     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2022-01-19T05:19:47.1902966Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
2022-01-19T05:19:47.1903504Z     at internal/main/run_main_module.js:17:47
2022-01-19T05:19:47.2199880Z # Subtest: ./packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts
2022-01-19T05:19:47.2200880Z     1..0 # no tests found
2022-01-19T05:19:47.2336186Z not ok 119 - ./packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts # time=20081.559ms
```

**Comment by awadhana** [comment]
> @awadhana Seems like something is not right with either .taprc or jest.config because it is failing on account of tap/tape trying to run a jestified test:
> 
> ```shell
> 022-01-19T05:19:36.1684499Z Unable to find Jest's global expect.
> 2022-01-19T05:19:36.1686007Z Please check you have added jest-extended correctly to your jest configuration.
> 2022-01-19T05:19:36.1687570Z See https://github.com/jest-community/jest-extended#setup for help.
> 2022-01-19T05:19:47.1802580Z /home/runner/work/cactus/cactus/packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts:2
> 2022-01-19T05:19:47.1803883Z import type { AddressInfo } from "net";
> 2022-01-19T05:19:47.1807366Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ^
> 2022-01-19T05:19:47.1891725Z ReferenceError: describe is not defined
> 2022-01-19T05:19:47.1894274Z     at Object.<anonymous> (/home/runner/work/cactus/cactus/packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts:2:2159)
> 2022-01-19T05:19:47.1896065Z     at Module._compile (internal/modules/cjs/loader.js:1072:14)
> 2022-01-19T05:19:47.1896992Z     at Module.replacementCompile (/home/runner/work/cactus/cactus/node_modules/append-transform/index.js:60:13)
> 2022-01-19T05:19:47.1897896Z     at Module.m._compile (/home/runner/work/cactus/cactus/node_modules/ts-node/src/index.ts:1311:23)
> 2022-01-19T05:19:47.1898766Z     at module.exports (/home/runner/work/cactus/cactus/node_modules/default-require-extensions/js.js:7:9)
> 2022-01-19T05:19:47.1899571Z     at /home/runner/work/cactus/cactus/node_modules/append-transform/index.js:64:4
> 2022-01-19T05:19:47.1900401Z     at require.extensions.<computed> (/home/runner/work/cactus/cactus/node_modules/ts-node/src/index.ts:1314:12)
> 2022-01-19T05:19:47.1901252Z     at Object.<anonymous> (/home/runner/work/cactus/cactus/node_modules/append-transform/index.js:64:4)
> 2022-01-19T05:19:47.1901842Z     at Module.load (internal/modules/cjs/loader.js:937:32)
> 2022-01-19T05:19:47.1902369Z     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
> 2022-01-19T05:19:47.1902966Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
> 2022-01-19T05:19:47.1903504Z     at internal/main/run_main_module.js:17:47
> 2022-01-19T05:19:47.2199880Z # Subtest: ./packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts
> 2022-01-19T05:19:47.2200880Z     1..0 # no tests found
> 2022-01-19T05:19:47.2336186Z not ok 119 - ./packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts # time=20081.559ms
> ```
@petermetz  hopefully solid now :)

**Comment by petermetz** [comment]
> @petermetz hopefully solid now :)

@awadhana Yup, it's legit, thank you for the fix!

**Pull request merged**
