### PR TITLE
docs(readme): add GIF showcasing the watch script

### PR DESCRIPTION
**Pull request by petermetz**
## Dependencies

Depends on #656 

## Commit to be reviewed

docs(readme): add reference to BUILD.md

BUILD.md: add GIF showcasing the watch script

We've received feedback from multiple people that long build
times are tedious and reduce general productivity which is
(probably) hindering the growth of the community so here is
a video guide (GIF) on how fast builds can be achieved by
only rebuilding what you actually changed on the package level.

It also comes with support for regenerating the code that we
don't write ourselves but use the OpenAPI generator for it instead.
All the openapi.json files are being watched by the npm run watch
script for code changes the same way that Typescript files are being
watched so this just works out of the box.

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

### CODE REVIEW

**Comment by petermetz** [comment]
@sfuji822 @takeutak Pushed changes according to the change requests.

**Review by jonathan-m-hamilton — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
@sfuji822 @takeutak Kindly requesting that you review this pull request. Thank you very much in advance.

**Comment by petermetz** [comment]
@sfuji822 @takeutak Kindly requesting that you review or follow-up on the review discussion within this pull request (whichever is applicable). Thank you very much in advance.

**Review by kikoncuo — APPROVED** [review]

**Comment by takeutak** [comment]
@petermetz Sorry for late replying. As we discussed on the contributors meeting 2021-03-16, would you move the gif image from top page to some sub directory?

**Review by takeutak — APPROVED** [review]

**Comment by petermetz** [comment]
> @petermetz Sorry for late replying. I missed updates of this PR. I approved it a moment ago.

@takeutak No worries, thank you!

**Pull request merged**
