### PR TITLE
feat(polkadot): polkadot-connector-first-implementation

### PR DESCRIPTION
**Pull request by CatarinaPedreira**
The first implementation of the Polkadot connector for Hyperledger Cactus.

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@CatarinaPedreira Please rebase + squash so that the conflicts are resolved, otherwise the CI won't run.

**Comment by CatarinaPedreira** [comment]
Sorry for the late reply Peter, will do in the weekend :)

**Comment by petermetz** [comment]
> Sorry for the late reply Peter, will do in the weekend :)

@CatarinaPedreira No worries, no rush :-)

**Comment by RafaelAPB** [comment]
@CatarinaPedreira Did you have time to incorporate the changes? This package would be useful for us to be able to connect to the SAIO and showcase a bug

**Comment by petermetz** [comment]
@CatarinaPedreira @RafaelAPB As usual, I'm happy to help with any git problems you might be having, nasty conflicts, etc.

**Comment by CatarinaPedreira** [comment]
I'm so sorry for the late reply - this last week and a half has been crazy busy at work. I haven't had the time yet, but I will take care of this asap (maximum on the weekend). So sorry and thank you for your patience. @RafaelAPB @petermetz

**Comment by petermetz** [comment]
@CatarinaPedreira No worries at all, I'm drowning in tasks myself as well. :-) If you need any help do not hesitate to reach out here with questions!

**Comment by RafaelAPB** [comment]
@CatarinaPedreira any updates on this?

**Comment by RafaelAPB** [comment]
@CatarinaPedreira this PR can be closed: i'll create a new one with the needed refactoring.

**Pull request closed without merging**
