### PR TITLE
style: 2021-09-20 linter warnings batch 23/26 fixes: #1371

### PR DESCRIPTION
**Pull request by zondervancalvez**
This is the recreation of PR of #1779
 
Reason for this new PR:
The previous repo was deleted.

### CODE REVIEW

**Comment by zondervancalvez** [comment]
Hello @petermetz , following this up for your review. Thank you

**Review by petermetz — CHANGES_REQUESTED** [review]
@zondervancalvez The diff is empty.

**Review by petermetz — APPROVED** [review]
@zondervancalvez Thank you, LGTM!

**Review by izuru0 — APPROVED** [review]
LGTM

**Pull request merged**
