### PR TITLE
test: jestify get consortium jws endpoint test

### PR DESCRIPTION
**Pull request by awadhana**
Migrated test from Tap to Jest.

File Path:
packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts

This is a PARTIAL resolution to issue #238

Signed-off-by: awadhana <awadhana0825@gmail.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@awadhana LGTM but before merging please make sure the PR description and the git commit are updated to not resolve the main jest issue.

**Comment by awadhana** [comment]
> @awadhana LGTM but before merging please make sure the PR description and the git commit are updated to not resolve the main jest issue.

@petermetz  Done :)

**Comment by petermetz** [comment]
@awadhana Great, thank you! Now it's time to resolve the conflicts that snuck in in the meantime. If you hit any problems with the JWS related code (there was a migration from the `jose` 1.x library version to 4.x) then I recommend reaching out to @jagpreetsinghsasan because he wrote the code for the migration PR.

**Review by petermetz — APPROVED** [review]
@awadhana LGTM, thank you!

**Review by jagpreetsinghsasan — APPROVED** [review]

**Pull request merged**
