### PR TITLE
test(verifier-client): add stress test and fix a memory leak

### PR DESCRIPTION
**Pull request by outSH**
- Add a new package `@hyperledger/cactus-test-verifier-client` for verifier-client stress and
  functional tests that involve multiple packages.
- Add stress test for verifier-client that reports memory usage of repeated operation
  on `cactus-plugin-ledger-connector-go-ethereum-socketio` connector plugin.
- Fix a memory leak in `SocketIOApiClient` - free socket listeners when they are no longer needed.
- Fix `cactus-plugin-ledger-connector-go-ethereum-socketio` - use single a web3 connection
  (with keep-alive/reconnect) instead of spawning new one for each request.
  Previous solution was causing connection issues in stress testing.

Depends on: https://github.com/hyperledger/cactus/pull/2089
Closes: https://github.com/hyperledger/cactus/issues/2189

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

-------------

Please review only the last commit, the others are dependencies.

### CODE REVIEW

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@outSH Please fix the merge conflicts and also squash+rebase!

**Comment by outSH** [comment]
@petermetz Done

**Review by petermetz — APPROVED** [review]
@outSH LGTM, thank you!

**Pull request merged**
