### PR TITLE
build: migrate to GitHub Container Registry when it hits GA

### LINKED ISSUE #995: build: migrate to GitHub Container Registry when it hits GA
### Description
As a maintainer I want to have automated checks stopping PRs which break the container image builds so that I don't unknowingly introduce bugs to the codebase when accepting a PR that looks okay but it's not. 

> Note: The Container registry is currently in public beta and subject to change. During the beta, storage and bandwidth are free. To use the Container registry, you must enable the feature preview. For more information, see "Introduction to GitHub Packages" and "Enabling improved container support with the Container registry."

Source: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

#### Why though?

Because Docker Hub (Docker Cloud) can only observe branches but not PRs (when the branch is not in the repo but on a fork)

### Acceptance Criteria
1. It is impossible to merge a pull request if it breaks any of the container images that we have
2. The checks are integrated into the standard PR process meaning that they show up as failing on the PR itself, there's no need to check any other places, it's all there on the bottom section of the PR page
3. All container images are covered that we have (this means that the existing bugs have to be fixed - we have some broken container image builds exactly because these checks are not in place at present so bugs in the Dockerfile's snuck in)

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz @arnab-roy @ryjones

### PR DESCRIPTION
**Pull request by petermetz**
1. Adds GitHub workflow files for publishing to GHCR upon commits and tags
  that happen *on* the ***main*** branch.
  2. Does not publish anything automatically when a pull request is opened,
  only when it is merged. This is important because it means that we still
  need to build the images as part of the PR builds so that it is ensured
  that the pull request changes are not breaking an image build by accident.
  3. It deletes all the **/hooks/post_push scripts from the repository because
  we no longer need those (they were part of the DockerHub integration
  which is what we are phasing out here)
  4. The tagging strategy remains as before: the date and the short hash
  are included for each main branch commit build and if a tag is created
  then that gets applied almost exactly as-is, but without the "v" prefix.
  5. Re-wrote the Fabric connector's README, specifically the part that
  refers to the old fabric 1 AIO image that used to be on DockerHub (it
  was deleted on 2021-12-21)
  6. Updated the vault keychain plugin server's container image documentation
  and the default image used by the test tooling class so that it no longer
  points to an already deleted DockerHub repo.
  7. Remove the explicit image name specification from the quorum tests so that
  the default gets applied from the `QuorumTestLedger` class. The test cases
  were declaring the old (DockerHub) image instead of the one from GHCR which
  is now the default in `QuorumTestLedger`.
  8. Updated the CONTRIBUTING.md because it had outdated references to the
  quorum and besu AIO images (DockerHub).
  
  Fixes #995
  
  Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

### CODE REVIEW

**Comment by petermetz** [comment]
@ryjones Do you see any `cactus-*` images on DockerHub that have been pulled recently? (which would indicate that I forgot to update tests somewhere to ghcr.io from dockerhub).
I know it's a chore to check them one by one, happy to do it myself just need permission to view them.

**Comment by ryjones** [comment]
@petermetz what is your DockerHub username?

**Comment by petermetz** [comment]
@ryjones Thank you, I'll get on it ASAP.

**Review by takeutak — APPROVED** [review]

**Comment by takeutak** [comment]
LGTM.  I'm sorry to review it late.

**Comment by petermetz** [comment]
@takeutak No worries, thank you for the review!

**Comment by petermetz** [comment]
@jagpreetsinghsasan ping

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Pull request merged**
