### PR TITLE
feat(cmd-socketio-server): support multiple BLP in single server

### LINKED ISSUE #2102: feat(cmd-socketio-server): support multiple BLP in single server
as of now, two BLPs cannot be loaded to one process.

although BLP has an identifier, the source code does not allow more than one BLP to be loaded.

this means a developer needs to write one BLP that has all endpoints for a service.

it is desirable if one server can load more than one BLP and 
combine them to create a service.

this would make it easier for a programmer to write a service by
reusing existing small, simple BLPs

this WI is to enable more than one BLP to exist in a process.

### PR DESCRIPTION
**Pull request by outSH**
- Add support for starting Cactus CMD SocketIO server with multiple Bussiness Logic Plugins (BLP).
  All required TransactionManagement request should be routed to the correct BLP.
- Add optional onListening callback when starting the cactus cmd socketio server, to simplify tests.
- Fix some bugs and hard-coded BLP Ids in TransactionManagement.
- Add new unit tests to check newly added functionalities.

Closes #2102

Depends on #2030

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

### CODE REVIEW

**Comment by outSH** [comment]
@jagpreetsinghsasan @izuru0 Please review (only the last commit)

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by petermetz — APPROVED** [review]
@outSH LGTM, thank you!

**Review by petermetz — CHANGES_REQUESTED** [review]
@outSH Please resolve the merge conflict and then we are good to go!

**Review by petermetz — APPROVED** [review]
@outSH Thank you! LGTM

At the same time though, I see this test failure which does not look like a flake. Could you please take a look?

```sh
FAIL packages/cactus-cmd-socketio-server/src/test/typescript/unit/cmd-socketio-blp-plugin.test.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/etc/cactus/validator-registry-config.yaml'

      67 |
      68 |   constructor(path: string) {
    > 69 |     const yamlText = fs.readFileSync(path, "utf8");
         |                         ^
      70 |     const yamlObj = yaml.safeLoad(yamlText);
      71 |     this.ledgerPluginInfo = yamlObj.ledgerPluginInfo;
      72 |     this.signTxInfo = yamlObj.signTxInfo;

      at new ValidatorRegistry (packages/cactus-cmd-socketio-server/src/main/typescript/verifier/validator-registry.ts:69:25)
      at Object.<anonymous> (packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/util/DBAccess.ts:18:43)
      at Object.<anonymous> (packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/util/LPInfoHolder.ts:8:1)
```

**Review by petermetz — CHANGES_REQUESTED** [review]
@outSH Please fix the merge conflict and then pass it back for review!

**Comment by outSH** [comment]
@petermetz Rebased and tested - ready to merge

**Review by petermetz — APPROVED** [review]
@outSH LGTM, thank you!

**Pull request merged**
