### PR TITLE
Docs : added a badge to open cactus with vscode

### LINKED ISSUE #1116: docs(README.md): add Open in VSCode badge
### Description
As a prospective contributor I want to have access to the quickest possible way to start working on Cactus code so that I'm more likely to end up contributing and also more productive while doing so.

Add a badge very similar to how it's shown here in the example:
https://code.visualstudio.com/updates/v1_58#_open-in-vs-code-badge

### Acceptance Criteria
1. Badge is on the README.md file in the project root, conveniently placed with the rest of the badges.
2. Clicking on the badge does indeed opens the project and after setup procedures have finished, the user can start writing code (similar experience to how the dev container works).

cc: @ty-lazar @Jeff-Ushry @twiggins120 @awadhana @Leeyoungone

### PR DESCRIPTION
**Pull request by shoebsd31**
Fixes #1116 
Signed-off-by: shoeb <shoebsd31@gmail.com>

### CODE REVIEW

**Comment by petermetz** [comment]
@shoebsd31 You need to reword the commit message to make it satisfy the formatting requirements. I recommend this as a commit message: `docs(README.md): add Open in VSCode badge #1116` (it's a copy paste of the issue that you are working on)

**Comment by shoebsd31** [comment]
> @shoebsd31 You need to reword the commit message to make it satisfy the formatting requirements. I recommend this as a commit message: `docs(README.md): add Open in VSCode badge #1116` (it's a copy paste of the issue that you are working on)

Hi Peter, I have updated the commit message

**Comment by petermetz** [comment]
@shoebsd31 You also need to squash the commits (right now the original commit remains with the non-formatted message)
https://github.com/hyperledger/cactus/pull/1118/commits

**Review by petermetz — CHANGES_REQUESTED** [review]
@shoebsd31 You also need to squash the commits (right now the original commit remains with the non-formatted message)
https://github.com/hyperledger/cactus/pull/1118/commits

**Comment by petermetz** [comment]
@shoebsd31 Happy to help if you need some assistance with the squashing BTW.

**Comment by shoebsd31** [comment]
> @shoebsd31 Happy to help if you need some assistance with the squashing BTW.

Hi Peter,

Thanks. I am just a bit occupied with work. I can fix it in the weekend. It would be great if you could squash it, if its urgent.

Regards,
Shoeb

**Comment by petermetz** [comment]
@shoebsd31 No rush, just wanted to make sure you are aware that there's help if needed. Weekend is fine (or the next, really not in a rush and thank you again for your contribution!)

**Comment by shoebsd31** [comment]
> @shoebsd31 No rush, just wanted to make sure you are aware that there's help if needed. Weekend is fine (or the next, really not in a rush and thank you again for your contribution!)

Hi Peter, I have squashed the commit and merged it through a separate branch. There's a commitlint error. Can you please let me know what it expects ? or is it because I have created a separate branch for merging ?

**Comment by petermetz** [comment]
> Hi Peter, I have squashed the commit and merged it through a separate branch. There's a commitlint error. Can you please let me know what it expects ? or is it because I have created a separate branch for merging ?

@shoebsd31 Yeah, if you click on `Details` next to the check then it will show an error message in your case it was about the subject having to be lowercase so I'd recommend changing the commit message like this:

From `docs(README.md): add Open in VSCode badge #1116`
To `docs(readme.md): add Open in VSCode badge #1116`

**Comment by shoebsd31** [comment]
> > Hi Peter, I have squashed the commit and merged it through a separate branch. There's a commitlint error. Can you please let me know what it expects ? or is it because I have created a separate branch for merging ?
> 
> @shoebsd31 Yeah, if you click on `Details` next to the check then it will show an error message in your case it was about the subject having to be lowercase so I'd recommend changing the commit message like this:
> 
> From `docs(README.md): add Open in VSCode badge #1116`
> To `docs(readme.md): add Open in VSCode badge #1116`

Thanks Peter!

**Comment by shoebsd31** [comment]
Hi @petermetz,

Can you please have a look at this one. I guess the merge is frozen for some reason. Rest looks fine, right?

**Comment by petermetz** [comment]
@shoebsd31 

> Can you please have a look at this one. I guess the merge is frozen for some reason.

I had to turn on the CI for it to run, did that just now.

> Rest looks fine, right?

You still have 2 separate commits in there that need to be squashed into a single one though. Once that's done we are good to go.

**Pull request closed without merging**
