### PR TITLE
fix(security): mitigate Cross-Site Scripting attack (XSS)

### PR DESCRIPTION
**Pull request by bhaskarvilles**
Unsanitized input from ```req.params``` flows into ```res.send```, where it is used to render an HTML page returned to the user. This may result in a Cross-Site Scripting attack (XSS)
Signed-off-by: Bhaskar <dev@bhaskar.email>

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@bhaskarvilles LGTM, please fix the commit linting issues.

**Comment by bhaskarvilles** [comment]
> @bhaskarvilles LGTM, please fix the commit linting issue.

Can you do it for me please ? My system has some errors with some packages with commitlint. I've invited you as a collaborator.

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by petermetz — APPROVED** [review]
@bhaskarvilles LGTM

**Comment by petermetz** [comment]
> > @bhaskarvilles LGTM, please fix the commit linting issue.
> 
> Can you do it for me please ? My system has some errors with some packages in commitlint. I've invited you as a collaborator.

@bhaskarvilles Alright. Let me take a look.

**Comment by petermetz** [comment]
@bhaskarvilles Re-requesting review from Izuru here was not necessary.

**Pull request closed without merging**
