### PR TITLE
fix: added a dummy package

### PR DESCRIPTION
**Pull request by elenaizaguirre**
added a dummy package for tests about install packages from github
sources required for #1210 

Signed-off-by: Elena Izaguirre <e.izaguirre.equiza@accenture.com>

### CODE REVIEW

**Review by petermetz — COMMENTED** [review]
@elenaizaguirre Quick question: Do we need the .d.ts files as well? And how about the openapi.json and the generated code files?
You see where this is going: I want to reduce the 32 files in the diff to the absolute minimum viable dummy package (which might be as low as two files, the package.json and an index.js) but I might be overlooking one (or many) things so that's why this is a question not necessarily a change request.

**Comment by takeutak** [comment]
@elenaizaguirre Thanks for contributing. Would you add the corresponding issue on Cactus GitHub? (If there is no corresponding issue, would you post the issue?)

**Comment by elenaizaguirre** [comment]
> @elenaizaguirre Quick question: Do we need the .d.ts files as well? And how about the openapi.json and the generated code files? You see where this is going: I want to reduce the 32 files in the diff to the absolute minimum viable dummy package (which might be as low as two files, the package.json and an index.js) but I might be overlooking one (or many) things so that's why this is a question not necessarily a change request.

@petermetz I have deleted *.d.ts files but I think openapi.json and generated code are necessary because the first one is required for some files and generated code is used because when we instantiate a plugin from the api server, it ensures that the plugin can call some methods:
```typescript
    const pluginPackage = require(/* webpackIgnore: true */ packagePath); // this one is our dummy package
    const createPluginFactory = pluginPackage.createPluginFactory as PluginFactoryFactory;
    const pluginFactoryOptions: IPluginFactoryOptions = {
      pluginImportType: pluginImport.type,
    };
    const pluginFactory = await createPluginFactory(pluginFactoryOptions);
    const plugin = await pluginFactory.create(pluginOptions);
    try {
      await plugin.onPluginInit();
```

It also calls `installOpenapiValidationMiddleware` with each endpoint of the plugin.

**Comment by elenaizaguirre** [comment]
> @elenaizaguirre Thanks for contributing. Would you add the corresponding issue on Cactus GitHub? (If there is no corresponding issue, would you post the issue?)

@takeutak Is not an issue by itself, it is the first step for a Peter suggestion  https://github.com/hyperledger/cactus/pull/1456#discussion_r745012362. Anyway, I've added the original issue number to the description

**Review by takeutak — APPROVED** [review]

**Comment by petermetz** [comment]
> @petermetz I have deleted *.d.ts files but I think openapi.json and generated code are necessary because the first one is required for some files and generated code is used because when we instantiate a plugin from the api server, it ensures that the plugin can call some methods:

@elenaizaguirre Could we just not have the plugin implement web services at all? If we limit our scope to the dummy package just being the testing instrument for verifying that the local file system path based plugin installation works then it doesn't matter if it's a web svc plugin or not IMO.

I mean something like this in an index.js file:
(pseudo-ish code, syntax might have small issues)

```js
class DummyPlugin {
  onPluginInit() {
    console.log("DummyPlugin#onPluginInit() OK");
    return Promise.resolve();
  }
}

class DummyPluginFactory {
  create() {
    return Promise.resolve(new DummyPlugin());
  }
}

module.exports.createPluginFactory = (options) => {
  return Promise.resolve(new DummyPluginFactory(options));
};
```

**Review by petermetz — COMMENTED** [review]
^^ See above

**Comment by elenaizaguirre** [comment]
> > @petermetz I have deleted *.d.ts files but I think openapi.json and generated code are necessary because the first one is required for some files and generated code is used because when we instantiate a plugin from the api server, it ensures that the plugin can call some methods:
> 
> @elenaizaguirre Could we just not have the plugin implement web services at all? If we limit our scope to the dummy package just being the testing instrument for verifying that the local file system path based plugin installation works then it doesn't matter if it's a web svc plugin or not IMO.
> 
> I mean something like this in an index.js file: (pseudo-ish code, syntax might have small issues, some more methods are probably missing but the point is that we only need to provide the simplest possible implementation that does not make it crash at install & instantiation time to verify that it can be installed from the local file-system without a crash)
> 
> ```js
> class DummyPlugin {
>   onPluginInit() {
>     console.log("DummyPlugin#onPluginInit() OK");
>     return Promise.resolve();
>   }
> }
> 
> class DummyPluginFactory {
>   create() {
>     return Promise.resolve(new DummyPlugin());
>   }
> }
> 
> module.exports.createPluginFactory = (options) => {
>   return Promise.resolve(new DummyPluginFactory(options));
> };
> ```

@petermetz Thanks, you were right, it was much simpler than I thought.

**Review by petermetz — APPROVED** [review]
@elenaizaguirre My pleasure and thank you very much for taking the time to address the nits as usual!

**Pull request merged**
