### PR TITLE
test: enhancement to check connection eth validator blp

### PR DESCRIPTION
**Pull request by StepniowskiP**
- Add tests for sync (read and write) requests to validator. 
- Add tests for async (read and write) requests to validator. 
- Add handling for Monitor Mode in blp. 
- Add tests for config files. Add automatization tools for tests and setup of blp.
-  Updated readme.

Depends on #1629

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@StepniowskiP LGTM as-is. Leaving it in "request changes" state for now because once the parent PR Is merged I will ask you to squash all the commits in here into a single one before we merge it to main.

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
@StepniowskiP FYI: the dependency checker robot does NOT understand `Depends on: #1629 ` but it does understand `Depends on #1629` in the PR description (e.g. the colon breaks the syntax).
I updated the PR description just now so that it picks it up (you can see it commenting above about it noticing the dependency)

**Review by petermetz — APPROVED** [review]
@StepniowskiP LGTM

**Pull request merged**
