### PR TITLE
refactor: versions in package json files

### PR DESCRIPTION
**Pull request by StepniowskiP**
Refactor of versions in package.json files to exact ones for more
reproducibity.

Closes: #1862
Signed-off-by: stepniowskip <piotr.stepniowski@fujitsu.com>

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@StepniowskiP Thank you very much! LGTM

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
@StepniowskiP Please resolve the conflicts and then we can merge.

**Review by petermetz — APPROVED** [review]
@StepniowskiP LGTM

Unrelated tip: GitHub recently started supporting rebase for updates instead of merge, you can select it by expanding the drop-down menu of the button that by default says `Update branch`
I recommend using the rebase instead of the merge option from the drop-down.

**Review by petermetz — CHANGES_REQUESTED** [review]
@StepniowskiP Please fix the conflicts and then we are good to go!

**Review by petermetz — APPROVED** [review]
@StepniowskiP LGTM

**Pull request merged**
