### PR TITLE
fix: openapi validation test for iroha plugin

### LINKED ISSUE #1331: fix(cactus-plugin-connector-iroha): Implement tests for openapi validation
**Describe the bug**

After implement openapi validation in plugins endpoints in cmd-api-server (#847), we must ensure that all endpoints in cactus-plugin-ledger-iroha are validated according package openapi specs.

Specific tests are needed.

**To Reproduce**

Call endpoints throught package API client with right and wrong requests.

**Expected behavior**

Right requests should return status code 200 and wrong requests should return status code 400.

**Hyperledger Cactus Plugins/Connectors Used**

 - cactus-plugin-ledger-iroha

### PR DESCRIPTION
**Pull request by elenaizaguirre**
Includes test for endpoint runTransactionV1
with test cases:
  - Right request
  - Request including an invalid parameter
  - Request without a required parameter

Closes #1331

Related with #847

Signed-off-by: Elena Izaguirre <e.izaguirre.equiza@accenture.com>

### CODE REVIEW

**Comment by elenaizaguirre** [comment]
@petermetz In this plugin two endpoints are defined but I think that invokeContractV1 is not implemented. Can you double check it, please? Should I remove that endpoint from specs?

**Review by petermetz — APPROVED** [review]

**Review by takeutak — APPROVED** [review]

**Comment by petermetz** [comment]
@elenaizaguirre Are the tests for iroha passing for you locally?

**Review by petermetz — COMMENTED** [review]
@elenaizaguirre Are the tests for iroha passing for you locally?

**Comment by elenaizaguirre** [comment]
> @elenaizaguirre Are the tests for iroha passing for you locally? I think they broke at some point (unrelated to this PR) and the best chance we have right now is to skip them to fix the CI, but before we go there please double check if the Iroha tests pass locally.

@petermetz Yes, this test is passing for me, and tests which are failing here are passing for me locally too

**Comment by petermetz** [comment]
@elenaizaguirre Okay, thank you for confirming. Since the tests are working for you locally, but they appear to be flaky on the CI, I'll ask that for now you mark the test as skipped (the one that's been failing according to the logs of the CI: `packages/cactus-test-tooling/src/test/typescript/integration/iroha/iroha-test-ledger/constructor-validates-options.test.ts`)

**Comment by elenaizaguirre** [comment]
> @elenaizaguirre Okay, thank you for confirming. Since the tests are working for you locally, but they appear to be flaky on the CI, I'll ask that for now you mark the test as skipped (the one that's been failing according to the logs of the CI: `packages/cactus-test-tooling/src/test/typescript/integration/iroha/iroha-test-ledger/constructor-validates-options.test.ts`)

@petermetz Done!

**Pull request merged**
