### PR TITLE
fix(cmd-socketio-server): mitigate cross site scripting attack

### PR DESCRIPTION
**Pull request by bhaskarvilles**
# Commit to be reviewed
--------------------------------

fix(cmd-socketio-server): mitigate cross site scripting attack

    Primary Changes
    ------------------
    1. Updated cactus-cmd-socketio-server/src/main/typescript/routing-interface/routes/index.ts 
    to mitigate the xss attack

### CODE REVIEW

**Review by izuru0 — COMMENTED** [review]
@bhaskarvilles thanks for the pull request. 
The changes to the code itself looks fine to me, but it seems your pull request isn't conforming to the convention. Please see the checklist in CONTRIBUTING.md.

**Comment by bhaskarvilles** [comment]
> @bhaskarvilles thanks for the pull request. The changes to the code itself looks fine to me, but it seems your pull request isn't conforming to the convention. Please see the checklist in CONTRIBUTING.md.
Added you as collaborator please resolve the commitlint issues and DCO issue, my system has some package errors with those programs, still resolving them :)

**Comment by takeutak** [comment]
@bhaskarvilles Sorry for my replying.  It seems that the commit message does not satisfy the [Conventional Commits syntax](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) as the CONTRIBUTING.md says.  Could you try to change your commit message using the following 'Changing older commit messages' on the following website?
  - https://www.educative.io/answers/how-to-change-a-git-commit-message-after-a-push 
If there are any troubles, please feel free to post on this thread.

@jagpreetsinghsasan About the PR error, is it all right with the above correspondence? Please let me know if there is any shortage.

**Comment by jagpreetsinghsasan** [comment]
> @bhaskarvilles Sorry for my late replying. It seems that the commit message does not satisfy the [Conventional Commits syntax](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) as the CONTRIBUTING.md says. For example, the following commit message satisfies the above: **"fix: migitate cross site scripting attack (XSS)"** (the prefix is needed).
> 
> Could you try to change your commit message using the following 'Changing older commit messages' on the following website?
> 
> * https://www.educative.io/answers/how-to-change-a-git-commit-message-after-a-push
> 
> If there are any troubles, please feel free to post on this thread.
> 
> @jagpreetsinghsasan About the PR error, is it all right with the above correspondence? If there are any problems, I'd like to borrow your help.

@takeutak  This is all correct.
I would like to add the exact steps in case its becoming tough. (There can be multiple ways to achieve the final goal, but this is something I generally do for fixing DCO and commit message linting issues) 
*NOTE* : Please make sure you create another branch out of this PR branch before doing the below changes, so that if something's wrong, you have the current code backed up in that other branch.

1. Update the remote cactus main branch
2. Rebase this PR branch onto the cactus remote main branch and then reset the PR branch onto the cactus remote main branch.
3. Perform the `git add .` (or the relevant files) and then `git commit -s` . This will open the editor for the commit message.
You can then paste the below commit message into the editor and save the file


> feat(socketio-server): cross site scripting attack
> 
>    Primary Changes
>    ------------------
>    1. Updated packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/routes/index.ts 
to mitigate the xss attack

(If there are any linting issues in this step, please rectify accordingly (can be like, the number of characters per line exceeded, etc etc.. which can be fixed accordingly)
4. Push the commit using `git push -f`
5. Once pushed, you can edit the PR message itself with the above commit message for easier readibility of the code change later on.

**Review by takeutak — APPROVED** [review]

**Comment by jagpreetsinghsasan** [comment]
We just need one squash merge of all the commits pending.

**Comment by bhaskarvilles** [comment]
Just added @jagpreetsinghsasan as collaborator, please do squash and commit changes.

**Comment by bhaskarvilles** [comment]
Give me the commands I'll squash and merge it.

**Comment by jagpreetsinghsasan** [comment]
NOTE:: [Create a branch out of your main branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository)  so that if any step fails, you still have the original code

Firstly checkout to your main branch as
`git checkout main`

Then, add cactus remote as
`git remote add cactus https://github.com/hyperledger/cactus.git`

Then, fetch the main branch code of cactus remote as
`git fetch cactus main`

Then, find the most recent common commit between cactus/main and your main, and then reset your main branch code onto that, as
`git reset $(git merge-base cactus/main main)`

Add the changes as
`git add -A`

Add the commit message using
`git commit -s`

This will open the text editor for adding the commit message
Add the following, in the text editor window

```
feat(socketio-server): cross site scripting attack
 
    Primary Changes
    ------------------
    1. Updated cactus-cmd-socketio-server/src/main/typescript/routing-interface/routes/index.ts 
    to mitigate the xss attack
```


Save the message and close the editor

Force push the changes as,
`git push --force`

**Comment by bhaskarvilles** [comment]
@jagpreetsinghsasan done:)

**Comment by bhaskarvilles** [comment]
@jagpreetsinghsasan merge now...

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM.
Thanks @bhaskarvilles for the contribution.

**Comment by bhaskarvilles** [comment]
@jagpreetsinghsasan can i get any bounty regarding this fix ?

**Comment by petermetz** [comment]
> @jagpreetsinghsasan can i get any bounty regarding this fix ?

@bhaskarvilles I'm not sure TBH. I wasn't aware of us having a bounty for security bugs. Did you find/submit a bounty on HackerOne or something where the bounties would be administered by the HL or LF foundation? (I'm not saying that this is a thing, just that if it was maybe that's how it would work)

Maybe @ryjones or @hartm knows something that I don't, if so, please chime in :-)

**Review by petermetz — APPROVED** [review]
@bhaskarvilles LGTM, thank you!

**Comment by petermetz** [comment]
@takeutak Please use rebase when updating the pull requests so that an explicit merge commit is not created like it was here:

image

**Comment by ryjones** [comment]
@bhaskarvilles submit an issue oh h1 and I’ll award you $100, even though cactus is outside the program

**Comment by bhaskarvilles** [comment]
@ryjones Please review this submission [report](https://hackerone.com/reports/1638984)

**Pull request merged**
