### PR TITLE
test: jestify new-contract-endpoint-invalid test

### PR DESCRIPTION
**Pull request by awadhana**
Migrated test from Tap to Jest.

File Path:
packages/cactus-test-plugin-htlc-eth-besu/src/
test/typescript/integration/plugin-htlc-eth-besu/
new-contract-endpoint-invalid.test.ts

This is a PARTIAL resolution to issue #238

Signed-off-by: awadhana <awadhana0825@gmail.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — APPROVED** [review]
@awadhana LGTM, thank you!

**Comment by petermetz** [comment]
@awadhana This one needs some conflict resolution after the last merge.

**Comment by awadhana** [comment]
> @awadhana This one needs some conflict resolution after the last merge.

@petermetz  ready for re-review :)

**Comment by petermetz** [comment]
@awadhana Now it has another one... sorry :-)

**Comment by awadhana** [comment]
No problemo, should be solid now hopefully 👍🏼

**Comment by petermetz** [comment]
@awadhana Now it looks like the jest config or the taprc file got tangled up again because the CI is failing with an error message that indicates that a tap+tape based test file is being executed by Jest (and failing of course)

**Comment by awadhana** [comment]
> @awadhana Now it looks like the jest config or the taprc file got tangled up again because the CI is failing with an error message that indicates that a tap+tape based test file is being executed by Jest (and failing of course)
> 
> This probably happened because other PRs got merged in the meantime as well, to fix you can probably just see which test file it was and then rectify the problem with the usual rebase

Got it :)

**Pull request merged**
