### PR TITLE
feat(connector-iroha2): wait for transaction commit

### PR DESCRIPTION
**Pull request by outSH**
- Add a new argument to transact endpoint to wait for transaction commit. When this flag is true, request will return with final transaction status (commit / reject).
- Add new transaction hash to all the responses from the transact endpoint.
- Alter tests to wait for status instead of waiting for X seconds to make them more reliable.
- Add new tests to check this PR features.

Relates to https://github.com/hyperledger/cactus/issues/2077

Depends on https://github.com/hyperledger/cactus/pull/2168

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

### CODE REVIEW

**Comment by jagpreetsinghsasan** [comment]
A major question here. Why are we having the iroha2 plugin seperate? Are the changes not relevant with the  v1 of Iroha, like in HL Fabric (v1.x and v2.x)?

**Comment by outSH** [comment]
> A major question here. Why are we having the iroha2 plugin seperate? Are the changes not relevant with the v1 of Iroha, like in HL Fabric (v1.x and v2.x)?

@jagpreetsinghsasan Iroha V2 is a complete redo of Iroha V1, including entire implementation and overall design and, what is important from our perspective, the API and the client libraries. There' no common code with Iroha 1 connector, hence the need for new Iroha2 connector.

**Comment by jagpreetsinghsasan** [comment]
> > A major question here. Why are we having the iroha2 plugin seperate? Are the changes not relevant with the v1 of Iroha, like in HL Fabric (v1.x and v2.x)?
> 
> @jagpreetsinghsasan Iroha V2 is a complete redo of Iroha V1, including entire implementation and overall design and, what is important from our perspective, the API and the client libraries. There' no common code with Iroha 1 connector, hence the need for new Iroha2 connector.

I see. Maybe we can remove the Iroha v1 plugin later on, once the Iroha community says its deprecated and just rename iroha2 plugin as iroha plugin.

**Review by jagpreetsinghsasan — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@outSH Please resolve the merge conflicts! (also squash+rebase)

**Pull request closed without merging**
