### PR TITLE
docs(whitepaper): split whitepaper

### LINKED ISSUE #405: docs(whitepaper): split whitepaper into multiple files
### Description
As a person contributing to the whitepaper I do not want to be blocked by pending PRs on sections of the whitepaper that are not related to another section that I wish to update so that I don't have to be concerned about producing difficult to resolve merge conflicts.

### Acceptance Criteria
1. Whitepaper is broken up into separate .md files at least a new file for each top level section that we have
2. PDF build still works
3. HTML build still works

cc: @takeutak @jonathan-m-hamilton @sfuji822

### PR DESCRIPTION
**Pull request by AzaharaC**
Resolve #405 
Depends on #706  (To work on Ubuntu 18)

### CODE REVIEW

**Comment by takeutak** [comment]
@AzaharaC Thank you for your suggestion!
However, I cannot find a reasonable reason for dividing whitepaper into chapters. Since the release of V0.4 is near, I would like to postpone the discussion until the release of V0.4 is completed.

**Review by petermetz — CHANGES_REQUESTED** [review]
@AzaharaC Looks awesome, just gonna ask that you rebase it onto the branch with the changes/fixes to containerize the HTML/PDF build and then it's good to go AFAIC. 
The rebase is needed so that there won't be conflicts/surprises with this one when it gets approved and it's time to merge (for example I saw that this one still puts the pdfs onto the ./whitepaper/ directory but with the other branch they'll all go under ./whitepaper/build/ )

**Comment by petermetz** [comment]
@AzaharaC Do you need any help with this?

**Comment by AzaharaC** [comment]
> @AzaharaC Do you need any help with this?

I have been seeing this issue on the icebox for a long time but now, that it is back in review, I am going to update it.

**Review by petermetz — APPROVED** [review]

**Comment by AzaharaC** [comment]
> @AzaharaC Thank you for your suggestion!
> However, I cannot find a reasonable reason for dividing whitepaper into chapters. Since the release of V0.4 is near, I would like to postpone the discussion until the release of V0.4 is completed.
> Is it possible to discuss it after the release of V0.4?

@takeutak Could you review this pr again? We believe that it is necessary to avoid having a single document that is too large and that it is easier to find the sections of interest for each person. If you want to discuss the need for this pr, we can do it with @petermetz at the next meeting we have.

**Comment by takeutak** [comment]
@AzaharaC Sorry for my late replying (due to the consecutive national holidays in my country).
In your suggestion, I am worried that the readability of the markdown document will decrease since the whitepaper is separated to multiple files. I'm sure that the readability of the markdown file itself is also important.

If you want to discuss the need for this pr, we can do it with @petermetz at the next meeting we have.

Thanks. Would you discuss about this topic on the next meeting?

**Comment by AzaharaC** [comment]
@takeutak I understand your concern on this issue.
I will talk to Peter to see if he can add this point to the next meeting, so I can discuss it with him.

**Comment by petermetz** [comment]
@takeutak 

> the collision should be solved even if the whitepaper is one file.

Do you mean that merge conflicts will not happen?

**Comment by takeutak** [comment]
@petermetz Sorry for late replying.
I mean that the possibility of conflicts does not change before and after splitting the paper.
In GitHub file changes are made for each line of a file. If there is some conflict, more than two people are editing the same line one time. The risk does not changed by splitting the paper.

**Comment by petermetz** [comment]
@takeutak 

> In GitHub file changes are made for each line of a file. If there is some conflict, more than two people are editing the same line one time. 

How do you account for changes that are triggered outside of the line that you changed? 
Example: Person A and B both add a new section to the whitepaper which changes the table of contents and also changes the numbering on a dozen other places due to everything having to be re-organized and these end up conflicting?

**Comment by petermetz** [comment]
# An Intro to Cactus

1) Abstract 
2) Introduction to Blockchain Interoperability
3) Use-cases
4. Software Design - 4.1. Principles

7. Terminology (split between the intro and the Architectural details and specs)

8. Related Work

9. References (to be split between the two new documents)

10. Recommended Reference


# Architectural details and specs

4.2 Feature Requirements
  4.2.1 New Protocol Integration
  4.2.2 Proxy/Firewall/NAT Compatibility
  4.2.3 Bi-directional Communications Layer
  4.2.4 Consortium Management
4.3 Working Policies
5. Architecture
6. Identities, Authentication, Authorization 
   > RENAME section from "Identities, Authentication, Authorization " to "Extension Plugins"
   > Distinguish between connector plugins and extension plugins such as keychains, HTLC, etc.

7. Terminology (split between the intro and the Architectural details and specs)

9. References (to be split between the two new documents)

**Comment by petermetz** [comment]
Alright, let's pick this up another time then.

**Pull request closed without merging**
