### PR TITLE
feat(draft): can not create burrow docker

### PR DESCRIPTION
**Pull request by jscode017**
Signed-off-by: jsjs026 <jasonhack518@gmail.com>

### CODE REVIEW

**Comment by jscode017** [comment]
using `npx tap --timeout=600 packages/cactus-test-tooling/src/test/typescript/integration/burrow/burrow-test-ledger` to run /packages/cactus-test-tooling/src/main/typescript/burrow
From the container log,  running burrow image would trigger `{"caller":"pex_reactor.go:533","component":"tendermint","height":1,"log_channel":"Info","message":"No addresses to dial. Falling back to seeds","module":"pex","run_id":"86953d26-beda-11eb-8a1e-a5bf42f90537","scope":"tendermint.NewNode","time":"2021-05-27T10:59:23.6991219Z"}`

**Comment by jscode017** [comment]
@petermetz

**Comment by petermetz** [comment]
@jscode017 I think it might be the health check not working as expected and then because of that the start method of `BurrowTestLedger` never returns (resolves the promise).

I got this when I tried to run your test:

```log
TAP version 13
# Subtest: constructor throws if invalid input is provided
    ok 1 - expect truthy value
    ok 2 - expected to throw
    1..2
ok 1 - constructor throws if invalid input is provided # time=6.156ms

# Subtest: constructor does not throw if valid input is provided
    ok 1 - expect truthy value
    ok 2 - expected to not throw
    1..2
ok 2 - constructor does not throw if valid input is provided # time=2.106ms

[2021-05-27T21:44:41.010Z] ERROR (burrow-test-ledger): hyperledger/burrow:0.32.1
[2021-05-27T21:44:45.606Z] ERROR (burrow-test-ledger): hyperledger/burrow:0.32.1
[2021-05-27T21:44:45.609Z] ERROR (burrow-test-ledger): starting container
# Subtest: starts/stops/destroys a docker container
    not ok 1 - http://0.0.0.0:50072 BurrowTestLedger#waitForHealthCheck() timed out (120000ms) -> Error: Parse Error: Expected HTTP/     at Socket.socketOnData (_http_client.js:469:22)     at Socket.emit (events.js:310:20)     at addChunk (_stream_readable.js:286:12)     at readableAddChunk (_stream_readable.js:268:9)     at Socket.Readable.push (_stream_readable.js:209:10)     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
      ---
      stack: >
        BurrowTestLedger.waitForHealthCheck
        (packages/cactus-test-tooling/src/main/typescript/burrow/burrow-test-ledger.ts:228:17)
      
        runMicrotasks (<anonymous>)
      at:
        line: 228
        column: 17
        file: packages/cactus-test-tooling/src/main/typescript/burrow/burrow-test-ledger.ts
        function: BurrowTestLedger.waitForHealthCheck
      tapCaught: returnedPromiseRejection
      test: starts/stops/destroys a docker container
      source: |2
                if (Date.now() >= startedAt + timeoutMs) {
                  throw new Error(
        ----------------^
                    `${httpUrl} ${fnTag} timed out (${timeoutMs}ms) -> ${ex.stack}`,
                  );
      ...
    
    1..1
    # failed 1 test
not ok 3 - starts/stops/destroys a docker container # time=124682.411ms

1..3
# failed 1 of 3 tests
# time=127065.702ms
Waiting for the debugger to disconnect...
```

**Comment by petermetz** [comment]
@jscode017 Yepp, it was the healthcheck, see the 2 commits I just added to your branch, now the test says

```sh
TAP version 13
# Subtest: constructor throws if invalid input is provided
    ok 1 - expect truthy value
    ok 2 - expected to throw
    1..2
ok 1 - constructor throws if invalid input is provided # time=6.046ms

# Subtest: constructor does not throw if valid input is provided
    ok 1 - expect truthy value
    ok 2 - expected to not throw
    1..2
ok 2 - constructor does not throw if valid input is provided # time=2.441ms

[2021-05-27T22:20:45.549Z] ERROR (burrow-test-ledger): hyperledger/burrow:0.32.1
[2021-05-27T22:20:46.915Z] ERROR (burrow-test-ledger): hyperledger/burrow:0.32.1
[2021-05-27T22:20:46.918Z] ERROR (burrow-test-ledger): starting container
# Subtest: starts/stops/destroys a docker container
    ok 1 - expect truthy value
    ok 2 - expect truthy value
    ok 3 - expect truthy value
    ok 4 - getGrpcPublicPort() returns truthy OK
    ok 5 - getGrpcPublicPort() returns finite OK
    ok 6 - HostPort 50078 is reachable via localhost
    1..6
ok 3 - starts/stops/destroys a docker container # time=3391.353ms

1..3
# time=5745.189ms
```

**Comment by jscode017** [comment]
@petermetz  Thanks a lot, it works. Being stuck on this for days , really appreciate it.

**Comment by petermetz** [comment]
@jscode017 No worries, I'm glad to help!

**Pull request closed without merging**
