### PR TITLE
fix(examples/discounted_cartrade): update the cert and private key at…

### PR DESCRIPTION
**Pull request by t-yasushi**
This PR resolves part of Issue #1181
In this PR, I update the cert and private key at default.json to activate trade process in discouted-cartrade.

Signed-off-by: Yasushi Takahashi <t-yasushi@fujitsu.com>

### CODE REVIEW

**Comment by t-yasushi** [comment]
This PR resolves Issue #1181

**Comment by t-yasushi** [comment]
This PR resolves Issue #1181

**Comment by t-yasushi** [comment]
This PR resolves Issue #1181

**Comment by t-yasushi** [comment]
Sorry, the commit message of this PR is too long. I will revise it tomorrow.

**Comment by t-yasushi** [comment]
> Sorry, the commit message of this PR is too long. I will revise it tomorrow.

I modified the commit message.

**Review by petermetz — CHANGES_REQUESTED** [review]
@t-yasushi Please squash the commits into one and then it's good to go from my side!

**Comment by t-yasushi** [comment]
> @t-yasushi Please squash the commits into one and then it's good to go from my side!

So, should I close this PR and make a new PR?

**Review by takeutak — APPROVED** [review]

**Comment by t-yasushi** [comment]
I just found out that there is a git squash command.
I squash 3 commits into 1!

**Review by petermetz — APPROVED** [review]

**Pull request merged**
