### PR TITLE
build(github): use dependent-issues action

### PR DESCRIPTION
**Pull request by z0al**
Hey there :wave:,

This is an ***automated PR*** to migrate recent [DEP](https://github.com/apps/dep) App users to a new [GitHub action](https://github.com/features/actions) called [Dependent Issues]( https://github.com/marketplace/actions/dependent-issues). 

If you received this PR it means you have DEP installed on the organization level (not necessarily enabled on this repository). If you think this is a mistake, I'm sorry. Please close this PR.

### :newspaper: TLDR

* The current DEP app has _been deprecated in favor of the new [Dependent Issues](https://github.com/marketplace/actions/dependent-issues)_ Github Action and it will be removed soon.
* The new Action works the same way the bot did but with additional features/changes:
  - Works with both _PRs and issues_ (disabled by default).
  - Works with _cross-repository_ dependencies e.g. `microsoft/vscode#999`.
  - It _notifies users by writing a comment_ with the list of dependencies and keep their states updated. This is especially useful when having the action enabled for non-PR issues.
  - Keywords and the label _can now be customized._
  - It sets the state of the head commit on a PR _to `pending` instead of `failure`_ (shows as :orange_circle: instead of a :x: ) when some dependencies are not yet ready (i.e. closed).

Breaking changes? Nothing. You can use the action the same way as before. eg. Writing `Depends on #number` or `Depends on owner/repo#number` clause(s) on the PR/issue description.

For more info please visit :point_right:  https://github.com/marketplace/actions/dependent-issues

### :bulb: Usage

example

### CODE REVIEW

**Comment by petermetz** [comment]
@z0al This looks good to me, but I see that you closed the PR after submitting it so now I have to ask why? :-)

**Comment by z0al** [comment]
Hey @petermetz . Thanks for checking this. The automated script opened so many PRs by mistake :sweat_smile: so I chose to close them all and let people reach out if it wasn't.

Here we go :)

**Comment by z0al** [comment]
`Error: Resource not accessible by integration`

The check currently fails because the `GITHUB_TOKEN` has read-only permissions because I forked the repo and don't have write permissions. GitHub won't run the checks against my fork but rather the source repo (this).

It should work fine after it gets merged. If not, please reach out.

**Comment by petermetz** [comment]
> `Error: Resource not accessible by integration`
> 
> The check currently fails because the `GITHUB_TOKEN` has read-only permissions because I forked the repo and don't have write permissions. GitHub won't run the checks against my fork but rather the source repo (this).
> 
> It should work fine after it gets merged. If not, please reach out.

@z0al Sounds good, thank you for the explanation on that! Last thing we need then is an administrative/legal chore (sorry) where we need to ask you to sign off your commit in the PR as per https://github.com/hyperledger/cactus/pull/396/checks?check_run_id=1460333895

It's actually pretty easy to do if you already have git signing keys set up (if not, then you'll need that first though). Happy to help either way, just let me know.

**Review by petermetz — APPROVED** [review]
@z0al Thank you very much!

**Review by jonathan-m-hamilton — APPROVED** [review]
LGTM

**Review by takeutak — APPROVED** [review]
LGTM

**Pull request merged**
