### PR TITLE
refactor(examples): divide components into packages and examples

### PR DESCRIPTION
**Pull request by takeutak**
Regarding Issue #327
Fix PR #326 

After posting PR #326, some technical problem on my GitHub fork repository happened and I built my fork again, so I requested the same pull-request again. 

Signed-off-by: Takuma TAKEUCHI <takeuchi.takuma@fujitsu.com>

### CODE REVIEW

**Comment by takeutak** [comment]
Peter already posted some useful advice on my old PR #326 , then I will reply soon.

**Comment by takeutak** [comment]
I replied Peter's comments on PR #326 as the following.

> examples/cartrade/package.json
> Does the cartrade example come with it's own CI script and lerna package structure embedded or is it just a matter of copy paste?

No, this code does not have any CI script and lerna package.
This package.json is tailored to the existing package.json based on your previous advice.  Some parameters are not required by the program itself (I did it according to your advice.  To be honest, I'd like to remove these redundant parameters).

> packages/config/verifier-config.json: 4
> Does this file intended to be part of the published npm packages once we issue a release?

Packages are based on the assumption that they will be core packages.
Note that some fixed parmeters are currently written on some codes, such as the fourth line of verifier-config.json, but we intend to make them a little more usable in the future development.

> packages/package.json
> Does this file belong to a specific package or does it have some other purpose (because it's not under any of the package sub-folders but rather in the ./packages/ directory itself)

Yes.  This package.json is used for building the ts codes (business-logic-plugin, ledger-plugin, routing-interface) on packages.  Of course, if the architecture is blushed up in the future discussion, there is a possibility to review this range later.

> Is there a reason why you use the @hyperledger-labs scope instead of @hyperledger/cactus-...

No, I don't have any special reason. I have tried to match the existing package.json to your previous review as much as possible.  I agree with changing the name @hyperledger-labs/cactus to @hyperledger/cactus, so I revised my pull request reflecting the above request about this.
https://github.com/hyperledger/cactus/pull/333/commits/3e104a7e023dcd8ea4473fa499e64096d6fcb4c7
It has directly nothing to do with the review of the pull-request, would you mind if you change the package.json?

**Comment by takeutak** [comment]
I think I responded to Peter's request for modification in my comments above.   Could you confirm this pull-request again?

**Comment by petermetz** [comment]
> I replied Peter's comments on PR #326 as the following (Thanks for your advice, Peter!).
> 
> > examples/cartrade/package.json
> > Does the cartrade example come with it's own CI script and lerna package structure embedded or is it just a matter of copy paste?
> 
> No, this code does not have any CI script and lerna package. This package.json is tailored to the existing package.json based on your previous advice. Some parameters are not required by the program itself (I did it according to your advice. To be honest, I think it's also okay to remove these redundant parameters).

Apologies, I may have not expressed myself correctly earlier while giving advice. I'd rather keep the package.json files as [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) as possible so copy pasting the full package.json of the root directory is not the way I would go there, I'd rather only include the scripts/dependencies/etc. that are actually needed for the particular package. This has numerous advantages over copy pasting the full root package.json file to each package folder.


> > packages/config/verifier-config.json: 4
> > Does this file intended to be part of the published npm packages once we issue a release?
> 
> The packages are based on the assumption that they will be core components. Please note that some fixed parameters are currently written on some codes, such as the fourth line of verifier-config.json, but we intend to make them a little more usable in the future development.
> 

Understood, thank you.

> > packages/package.json
> > Does this file belong to a specific package or does it have some other purpose (because it's not under any of the package sub-folders but rather in the ./packages/ directory itself)
> 
> Yes. This package.json is used for building the ts codes (business-logic-plugin, ledger-plugin, routing-interface) on packages. Of course, if the architecture is blushed up in the future discussion, there is a possibility to review this range later.

Is there a reason why the existing build system that's been in place since May cannot be used for compiling these packages `(business-logic-plugin, ledger-plugin, routing-interface) on packages`?

> > Is there a reason why you use the @hyperledger-labs scope instead of @hyperledger/cactus-...
> 
> No, I don't have any special reason. I have tried to match the existing package.json to your previous review as much as possible. I agree with changing the name @hyperledger-labs/cactus to @hyperledger/cactus, so I revised my pull request reflecting the above request about this.
> [3e104a7](https://github.com/hyperledger/cactus/commit/3e104a7e023dcd8ea4473fa499e64096d6fcb4c7)
> It has directly nothing to do with the review of the pull-request, would you mind if you change the package.json?

Sorry, not sure what you mean there, which package.json would you like me to change and how?

**Comment by takeutak** [comment]
@petermetz Thank you for gentle advice!  I replied as the following:

> Apologies, I may have not expressed myself correctly earlier while giving advice. I'd rather keep the package.json files as DRY as possible so copy pasting the full package.json of the root directory is not the way I would go there, I'd rather only include the scripts/dependencies/etc. that are actually needed for the particular package. This has numerous advantages over copy pasting the full root package.json file to each package folder.

Thank you for your cool advice! What you are saying is "You should not quote more libraries in your code than you need." I also agree with you.
Removing the redundant part of package.json is one of the topics discussed, but the code is redundant and has no impact. I intend to issue a new pull-request as soon as possible to remove the redundant part. Could you approve this pull-request first?

> Is there a reason why the existing build system that's been in place since May cannot be used for compiling these packages (business-logic-plugin, ledger-plugin, routing-interface) on packages?

Yes. We are using the code that we have been developed since May.
Of course, it may be necessary to apply some of Peter's current codes to this example, but it should be discussed in another place (Issue, Pull request, etc.). However, as you have heard in the regular meeting, we are currently reviewing the architecture. As discussed in the discussion, if there is a change in the core package, it should be combined with the core package used in this sample app. I think it would be more constructive to discuss how to adapt to future development code than to adapt to legacy code until May.
In any case, this discussion is beyond the scope of this pull-request submission. There is a possibility that once the discussion has been settled to some extent, it will be discussed in another context.

Thanks for your intelligent advice. 

> Sorry, not sure what you mean there, which package.json would you like me to change and how?

I suggested to change "hyperledger-labs" to "hyperledger" in the following package-json.
 - https://github.com/hyperledger/cactus/blob/master/package.json#L2
Of course, this discussion is out of the range of this pull-request. Then, if you'd like to change so, would you mind if you make another issue or pull-request?

**Comment by petermetz** [comment]
@takeutak Cheers, replies inline as well.

> @petermetz Thank you for gentle advice! I replied as the following:
> 
> > Apologies, I may have not expressed myself correctly earlier while giving advice. I'd rather keep the package.json files as DRY as possible so copy pasting the full package.json of the root directory is not the way I would go there, I'd rather only include the scripts/dependencies/etc. that are actually needed for the particular package. This has numerous advantages over copy pasting the full root package.json file to each package folder.
> 
> Thank you for your cool advice! What you are saying is "You should not quote more libraries in your code than you need." I also agree with you.
> Removing the redundant part of package.json is one of the topics discussed, but the code is redundant and has no impact at all. I intend to post a new pull-request as soon as possible to remove the redundant part. Could you approve this pull-request first?
> 

Sure thing. 

> > Is there a reason why the existing build system that's been in place since May cannot be used for compiling these packages (business-logic-plugin, ledger-plugin, routing-interface) on packages?
> 
> Yes. We are using the code that we have been developed since May.

Clarification: What I meant by build system is for example if you run `npm run build` from the root directory. My current understanding is that if you run that command at the moment it will not compile `(business-logic-plugin, ledger-plugin, routing-interface)` (this could be my mistake in understanding of course)

> Of course, it may be necessary to apply some of Peter's current codes to this example, but it should be discussed in another place (Issue, Pull request, etc.). However, as you have heard in the regular meeting, we are currently reviewing the architecture. As discussed in the discussion, if there is a change in the core package, it should be combined with the core package used in this sample app. 

> I think it would be more constructive to discuss how to adapt to future development code than to adapt to legacy code until May if we discuss about it in the future development.

When you say `legacy code until May` which code do you refer to? The legacy code we had under `./contrib/Accenture/` has been deleted altogether some time ago. I'm just trying to make sure our terminology usage matches up so communication isn't going sideways.

> I suggested to change "hyperledger-labs" to "hyperledger" in the following package-json: https://github.com/hyperledger/cactus/blob/master/package.json#L2
> Of course, this discussion is out of the range of this pull-request. Then, if you'd like to change so, would you mind if you make another issue or pull-request?

Oh, I see now! It makes more sense now that I see we made the same mistake in the root `./package.json` file as well. 
I agree that `./package.json` is not relevant to this PR and I'll send a PR to fix that. 

The [review](https://github.com/hyperledger/cactus/pull/326#discussion_r513093139) I was sending was for `./packages/package.json` which is part of this pull request or at least was part of the pull request I was reviewing at the time.

**Review by petermetz — APPROVED** [review]

**Review by jonathan-m-hamilton — APPROVED** [review]
LGTM

**Comment by takeutak** [comment]
> Clarification: What I meant by build system is for example if you run npm run build from the root directory. My current understanding is that if you run that command at the moment it will not compile (business-logic-plugin, ledger-plugin, routing-interface) (this could be my mistake in understanding of course)

That's right. If you build on the top directory, the codes of business-logic-plugin, ledger-plugin, routing-interface are not compiled. The detail is described in cartrade/README <https://github.com/hyperledger/cactus/blob/master/examples/cartrade/README.md>.

> When you say legacy code until May which code do you refer to? The legacy code we had under ./contrib/Accenture/ has been deleted altogether some time ago. I'm just trying to make sure our terminology usage matches up so communication isn't going sideways.

Sorry, I misunderstood your opinion.  In any cases, now we are discussing about the merged plan of codes, so I'm sure that in the future discussion we needs to adapt our example apps to the codes conforming to our common specification proposal.

**Pull request merged**
