### PR TITLE
test(test-tooling): add corda 5 aio image #1479

### LINKED ISSUE #1479: test(test-tooling): add corda 5 RC all-in-one container image
This is a prerequisite for being able to develop the connector plugin support for 5.x.

Container boot steps when it starts:
1. It launches via the corda-cli a test net of the solar system demo as seen in [7], more useful details in [4]
2. healthcheck waits for the HTTP RPC API to be accessible and then starts passing

## Acceptance criteria

1. Single container (AIO) that can be used to simulate a Corda network (single node is fine to begin with if that is easier).
2. The container class in the test tooling package container class has the ability to expose the HTTP RPC port on a randomized one so that test cases can use it as they see fit
3. The container image includes/provides a corda-cli, see [6] for details.
4. The container works the following way when it is started:
5. The container image supports docker on docker (e.g. bind the host machine's docker /var/run/sock instead of running a fully encapsulated docker in docker setup the way the Fabric AIO does - we are moving away from DinD for easier debugging)
6. The container image is based on Ubuntu 20.04 LTS, 
7. The container image has the recommended JVM version for Corda 5.x (whatever that version may be) 
8. The container image has docker-compose installed
9. The container image is published onto ghcr.io as `ghcr.io/hyperledger/cactus-corda-5-all-in-one-solar`
10. The container image has all of its tags like this so that we can test different iterations over time as necessary: `ghcr.io/hyperledger/cactus-corda-5-all-in-one-solar:2021-??-??--test-1479`

## References

1. https://docs.r3.com/en/platform/corda/5.0-dev-preview-1.html
2. https://docs.r3.com/en/platform/corda/5.0-dev-preview-1/nodes/nodes-homepage.html
3. https://docs.r3.com/en/platform/corda/5.0-dev-preview-1/tutorials/overview.html
4. https://docs.r3.com/en/platform/corda/5.0-dev-preview-1/getting-started/setup-network.html
5. https://docs.r3.com/en/platform/corda/5.0-dev-preview-1/nodes/developing/expose-rpc/annotation.html
6. https://docs.r3.com/en/platform/corda/5.0-dev-preview-1/nodes/operating/cli-curl/cli-curl.html#use-the-corda-node-cli-to-interact-with-nodes-via-http-rpc
7. https://github.com/corda/corda5-solarsystem-contracts-demo

### PR DESCRIPTION
**Pull request by AzaharaC**
Resolve #1479

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@AzaharaC I made some tweaks, could you please grant me permission to the image [1] so that I can push the latest build? Other than that, LGTM!

https://github.com/orgs/hyperledger/packages/container/package/cactus-corda-5-all-in-one-solar

**Comment by AzaharaC** [comment]
> @AzaharaC I made some tweaks, could you please grant me permission to the image [1] so that I can push the latest build? Other than that, LGTM!
> 
> https://github.com/orgs/hyperledger/packages/container/package/cactus-corda-5-all-in-one-solar

@petermetz Ready! Can you check that you really have permissions to update the image?

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
@AzaharaC Got it, now it let me publish it as `ghcr.io/hyperledger/cactus-corda-5-all-in-one-solar:2022-01-13--test-1479`, thank you!

**Pull request merged**
