### PR TITLE
docs: update README

### PR DESCRIPTION
**Pull request by RafaelAPB**
The current README presents potentially outdated information that holds details that are better suitable for the whitepaper. It lacks instructions on how to build and run the project, which can frustrate newcomers. 

I would propose us to simplify the README of the project, and as the example section matures, provide a practical example.

### CODE REVIEW

**Comment by RafaelAPB** [comment]
We can add an updated version of the architecture, and forward readers to the whitepaper, as well

**Review by petermetz — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
@RafaelAPB Would be nice to have a more specific commit message. `Update README` can mean a lot of different things. I'd say something like `docs(readme): reference build instructions` for example.

**Comment by RafaelAPB** [comment]
I've chosen that specific message because the commit also removes parts of it. Would it still be reasonable to only refer the build instructions?

**Comment by petermetz** [comment]
> I've chosen that specific message because the commit also removes parts of it. Would it still be reasonable to only refer the build instructions?

Tough question. It definitely makes sense IMO to not just say `updated readme`, but how much explanation should fit in the commit subject line (the top line) is difficult to say. 
My personal take: I'd use the commit body (e.g. lines after the first) to explain the rest of the story like that the theoretic explanations have been removed in favor of the rest of the documentation which contains the same information. 
Something like that. :-)

**Comment by RafaelAPB** [comment]
Makes sense. Let's see first what the other reviewers think.

**Review by takeutak — CHANGES_REQUESTED** [review]
This is about the change request mentioned in the commit below.
https://github.com/hyperledger/cactus/pull/311/commits/3bfab322e0180b3a3176151fe2d2e5a90d8a5092

**Review by takeutak — COMMENTED** [review]
I have strengthened your proposal as the commit below.  The reason is written in the header of the commit below.  Do you have any comments?
https://github.com/hyperledger/cactus/commit/3bfab322e0180b3a3176151fe2d2e5a90d8a5092

**Comment by RafaelAPB** [comment]
I agree, @takeutak ! Thanks!

**Comment by petermetz** [comment]
CI is failing because of an unrelated problem: https://github.com/hyperledger/cactus/issues/319

**Review by takeutak — APPROVED** [review]
LGTM

**Review by jonathan-m-hamilton — APPROVED** [review]
LGTM, pending CI resolution

**Comment by RafaelAPB** [comment]
Done @petermetz , thanks!

**Comment by takeutak** [comment]
Excuse me, it look like that the current README ignores my suggestion.
Please wait for merging before solving the issue.

**Review by takeutak — CHANGES_REQUESTED** [review]
As I said the above, the current status ignores my above commit.  Then I canceled my LGTM at once.

**Comment by takeutak** [comment]
I pushed the following commit, which content is the same as the above my commit.
https://github.com/hyperledger/cactus/pull/311/commits/ab2542d4b0e2d53a95c19fa4c0270bca01319ff6

Now I approved this PR again.

**Review by takeutak — APPROVED** [review]
LGTM

**Pull request merged**
