### PR TITLE
feat(LedgerPlugin): add TransactionSigner on LedgerPlugin

### PR DESCRIPTION
**Pull request by takeutak**
Signed-off-by: Takuma TAKEUCHI <takeuchi.takuma@fujitsu.com>

- Related with Issue #708 
- Contents:
  - (Main) separate Transaction functions on BLP-examples to TransactionSigner on LedgerPlugin

### CODE REVIEW

**Comment by takeutak** [comment]
@petermetz @jonathan-m-hamilton I'm sorry to bother you, but could you review this PR?

**Review by petermetz — APPROVED** [review]

**Review by sfuji822 — APPROVED** [review]
LGTM

**Comment by takeutak** [comment]
@petermetz cc: @hartm @jonathan-m-hamilton @kikoncuo @sfuji822 
The following pull-request cannot be merged due to the CI check error.
https://github.com/hyperledger/cactus/pull/707
The cause of error is not the PR code but Peter's other code. I'm afraid it looks like an error in the CI check function. Could you investigate the cause and take action?

Looking at the list of pull-request, I see similar CI check error in most PRs other than this PR. Since the release of V0.4 is near, could you please solve it as soon as possible?
I am also going to issue a new PR depending on the PR, and I would like to include it in V0.4. I will ask for an early solution.

**Comment by takeutak** [comment]
@petermetz cc: @jonathan-m-hamilton @kikoncuo @hartm @sfuji822 
Regarding the problem with the above CI check tool, I succeeded in restarting the CI check without any error. I solved the problem of my PR707 for now. Thank you.

**Pull request merged**
