### PR TITLE
docs(api-table): update API table and description

### PR DESCRIPTION
**Pull request by izuru0**
- updated API table for socket.io verifier and validator.
- names are changed for consistency

This PR corresponds to issue #1320

Signed-off-by: Izuru Sato <sato.izuru@fujitsu.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@izuru0 Please fix the commit lint errors

**Comment by izuru0** [comment]
update the title of this PR, because commit lint complains 'scope must be lower-case [scope-case]'.

**Comment by izuru0** [comment]
@petermetz @takeutak 
Fixed lint problem. 
The original commit message started from 'docs(API-table):'.
New commit message starts from 'docs(api-table):'.

**Review by petermetz — APPROVED** [review]
@izuru0 Thank you very much, LGTM!

**Pull request merged**
