### PR TITLE
fix(security):Cross-Site Scripting attack (XSS)

### PR DESCRIPTION
**Pull request by bhaskarvilles**
Unsanitized input from an exception flows into send resulting XSS

### CODE REVIEW

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@bhaskarvilles LGTM on the code diff but please make sure to fix all the failing checks. Let me know if you need any help.

**Comment by petermetz** [comment]
@bhaskarvilles Closing this for now, please feel free to re-open anytime once you have time to fix the checks. Also let me know if you need any help with those. We have a daily pair programming call (weekdays) in the mornings (Pacific Time) that you can join to get hands-on help as well.

**Comment by bhaskarvilles** [comment]
> @bhaskarvilles Closing this for now, please feel free to re-open anytime once you have time to fix the checks. Also let me know if you need any help with those. We have a daily pair programming call (weekdays) in the mornings (Pacific Time) that you can join to get hands-on help as well.

I'm sorry for the late message, unfortunately my system has crashed and lost all data. Once all my data is restored I'll update ASAP

**Pull request closed without merging**
