### PR TITLE
docs: Update whitepaper.md with Ref [4] on blockchain migration

### PR DESCRIPTION
**Pull request by dilumb**
Added reference [4] to blockchain migration patterns and scenarios as suggested by Rafael Belchior.

### CODE REVIEW

**Comment by RafaelAPB** [comment]
@dilumb you need to sign your commit as instructed here: https://github.com/hyperledger/cactus/pull/248/checks?check_run_id=953201967

Moreover, it is not very clear to me how the paper you proposed implements a blockchain migration. If this paper is to be included, I propose you to detail the data migration patterns/data management challenges.

**Comment by petermetz** [comment]
@dilumb Thank you for the contribution! In general, looks good to me, but let's also wait to hear from @RafaelAPB on this one because that section is his work entirely.

Regarding the failing automated checks, please make sure to fix all of those otherwise we won't be able to merge it even if it is otherwise approved.
1. DCO: there's some links about this in the CONTRIBUTING.md document in the root of the project folder, if that doesn't help let me know, I can help out.
2. commitlint: You need to amend the git commit message to be more like the title of the PR (I see you edited that which is good, but we need the actual git commit to be that way as well). You can do that with git rebase or some GUI tool that supports it. Let me know if you need help, but first please try to go through the CONTRIBUTING.md to see if any of that helps. Once you updated the commit message on your local branch you will need to do a force push to your remote branch. Be careful with that if you are just starting out with git, it can erase your work if done incorrectly (this is a pretty simple case though).
3. Semantic pull request: this should be automatically resolved once you fix 2).

**Comment by dilumb** [comment]
> @dilumb you need to sign your commit as instructed here: https://github.com/hyperledger/cactus/pull/248/checks?check_run_id=953201967
> 
> Can you please provide details on the data migration patterns/data management challenges?

Happy to add more details. Let's discuss during our meeting.
Also, I messed up the commit. Didn't think failed commit was visible to you guys. Will see how to resolve this too

**Comment by dilumb** [comment]
Because I wasn't able to resolve issue on my side I ended up deleting on github.com repo (still have local files) before all your comments. There seems to be no easy fix other than starting a new. Thanks

**Pull request closed without merging**
