### PR TITLE
docs: broken links were fixed

### LINKED ISSUE #286: [Documentation] Links are broken
**Describe the bug**

Links in https://github.com/hyperledger/cactus/blob/master/docs/tutorials/simple-asset-transfer.md are broken

Specifically Link to Main Docs https://github.com/hyperledger/cactus/blob/master/docs/main/index.hmtl

And configure.sh

I found the link to simple-asset-transfer from https://www.hyperledger.org/blog/2019/11/20/accenture-open-sources-blockchain-integration-framework-as-a-hyperledger-lab

### PR DESCRIPTION
**Pull request by pret-a-porter**
Fixes #286

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
LGTM 
Thank you @pret-a-porter

**Comment by petermetz** [comment]
CI is failing because of an unrelated problem: https://github.com/hyperledger/cactus/issues/319

**Review by takeutak — APPROVED** [review]
LGTM.  Thanks for your maintenance of legacy code.

**Review by jonathan-m-hamilton — APPROVED** [review]
LGTM

**Pull request merged**
