### PR TITLE
fix(security):Cross-Site Scripting attack (XSS)

### PR DESCRIPTION
**Pull request by bhaskarvilles**
mitigate many fixes in many files in Examples and Packages

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@bhaskarvilles Could you please squash + rebase onto upstream main?

**Comment by bhaskarvilles** [comment]
> @bhaskarvilles Could you please squash + rebase onto upstream main?

Can you share exact commands here

**Comment by bhaskarvilles** [comment]
> @bhaskarvilles Could you please squash + rebase onto upstream main?

You're are a collaborator, can you fix the failing issues ?

**Comment by bhaskarvilles** [comment]
@ryjones can i get a bounty on this fix ?

**Comment by jagpreetsinghsasan** [comment]
> > @bhaskarvilles Could you please squash + rebase onto upstream main?
> 
> Can you share exact commands here

You can reuse the same commands I shared in your previous PR, here https://github.com/hyperledger/cactus/pull/2068#issuecomment-1169673908

**Comment by jagpreetsinghsasan** [comment]
@bhaskarvilles any updates on this PR?

**Comment by bhaskarvilles** [comment]
> @bhaskarvilles any updates on this PR?

Just now updated the PR

**Review by jagpreetsinghsasan — APPROVED** [review]

**Review by izuru0 — APPROVED** [review]
LGTM

**Pull request closed without merging**
