### PR TITLE
docs(htlc-coordinator): added the flow diagram

### LINKED ISSUE #603: feat(core-api): HTLC coordinator
To be defined if this needs to be separated into another plugin.

One of the main ideas around Cactus is that it should be running automating the interactions between different nodes.
We have working HTLCs which can work on different networks but right now they need to be executed manually.
We need a plugin which can be ran by Cactus users which automates inter-node interactions.
As a first instance, we can create the HTLC coordinator, which would be the plugin in charge of monitoring a network and automate all HTLC functionality.

After an HTLC is created, this plugin would be in charge of monitoring and automating claims and refunds.
The process would be:
1. The HTLC is created manually on DLT1 using the correspondent HTLC plugin
2. The matching HTLC is created manually on DLT2 using the correspondent HTLC plugin
3. The HTLC coordinator plugin ran by user 1 (In DLT1) detects the second contract has been deployed and executes the claim on DLT2
4. The HTLC coordinator plugin ran by user 2 (In DLT2) detects the second contract has been claimed and uses the now disclosed secret to claim his asset on DLT1

Optionally the HTLC coordinator could handle the HTLC creation process to minimize time conflicts around refund timings

Acceptance criteria:
* When an HTLC is created, the HTLC coordinator monitors event/transactions
* When a matching HTLC is created, the coordinator claims the resolution
* When an HTLC secret is disclosed, the HTLC coordinators uses it to release tokens

Parent: feat(core-api): atomic swaps with HTLCs #510

### PR DESCRIPTION
**Pull request by jordigiam**
Resolve #603

### CODE REVIEW

**Review by petermetz — APPROVED** [review]

**Comment by takeutak** [comment]
Thanks for your proposal.
As I commented on PR587, I reviewed it again including the latest HTLC PR (PR 873), but it seems like I am just throwing away the HTLC smart contract as I deploy it, and it is hard to understand the positioning of your HTLC, which is frankly what I am talking about.
I am sorry but I will have a vacation until next week, but I want to prepare the alternative plan as soon as possible. I am sorry to have kept you waiting so long.

**Comment by petermetz** [comment]
> Thanks for your proposal.
> As I commented on PR587, I reviewed it again including the latest HTLC PR (PR 873), but it seems like I am just throwing away the HTLC smart contract as I deploy it, and it is hard to understand the positioning of your HTLC, which is frankly what I am talking about.
> I am sorry but I will have a vacation until next week, but I want to prepare the alternative plan as soon as possible. I am sorry to have kept you waiting so long.

@takeutak Thank you too! Hope you'll have a great holiday!

> but it seems like I am just throwing away the HTLC smart contract as I deploy it

Throwing it away as in deleting it? From the ledger?

**Comment by sfuji822** [comment]
I put my detailed comments at Issue #603 with a suggested solution.
Can you give me your opinion for my observation first?
When we could clarify what to do, I will issue a Change Request to implement.
@kikoncuo @petermetz @jordigiam
Cc: @takeutak

**Comment by petermetz** [comment]
> I put my detailed comments at Issue #603 with a suggested solution.
> Can you give me your opinion for my observation first?
> When we could clarify what to do, I will issue a Change Request to implement.
> @kikoncuo @petermetz @jordigiam
> Cc: @takeutak

@sfuji822 Thank you for the response. CC-ing @jagpreetsinghsasan (did the same on the other thread)

**Comment by petermetz** [comment]
@jagpreetsinghsasan Is this being worked on by you or did it get resolved in some other PR concurrently?

**Comment by jagpreetsinghsasan** [comment]
@petermetz as per the discussion in #603, I have created a new issue #1180 to implement the HTLC coordinator as explained by @sfuji822 as a new example/implementation of HTLC.

This flow diagram refers to the flow diagram of the HTLC plugin, we have [here](https://github.com/hyperledger/cactus/tree/main/extensions/cactus-plugin-htlc-coordinator-besu)

**Comment by petermetz** [comment]
> 

@sfuji822 Is that all satisfactory in the context of this pull request?

**Review by takeutak — APPROVED** [review]

**Pull request merged**
