### PR TITLE
docs: adding example for besu private transactions

### PR DESCRIPTION
**Pull request by travis-payne**
Closes: 1213
Signed-off-by: Travis Payne <travis.payne@accenture.com>

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@travis-payne The commit message says that it's a breaking change, but doesn't look like it.
It's important to not mark it as a breaking change unless it really is because this will show up in the release notes of the next version. It would also trigger/force a major release in the automation (once we have that fully figured out)

**Review by petermetz — CHANGES_REQUESTED** [review]
@travis-payne The hashmark is missing from the issue comment where you say `closes ...`

**Comment by travis-payne** [comment]
@petermetz fixed both of these issues!

**Review by petermetz — APPROVED** [review]
@travis-payne  LGTM

**Review by takeutak — APPROVED** [review]

**Pull request merged**
