### PR TITLE
docs(contributing.md): explicit recommendation for avoiding global dependencies #585

### LINKED ISSUE #585: docs(contributing.md): explicit recommendation for avoiding global dependencies
Installing anything globally with npm is a bottomless pit of problems so we generally don't recommend to do it at all and thrive to have all the dependencies of the project self-contained so that when you run `npm run configure` it gives you as hands-off of an approach as possible without having to iterate through a list of additional, implicit dependencies in the global npm scope.

The contributing.md should state this explicitly and early on so that people can avoid mistakes related to this.

### PR DESCRIPTION
**Pull request by zackvilla**
docs(contributing.md): explicit recommendation for avoiding global dependencies #585

Signed-off-by: Zachary Villanueva <Zachary.Villanueva@ibm.com>

Fixes #585

### CODE REVIEW

**Comment by zackvilla** [comment]
In reference to issue #585 docs(contributing.md): explicit recommendation for avoiding global dependencies

**Review by petermetz — APPROVED** [review]
@zackvilla This is great, thank you very much! To pass the semantic PR check please amend your commit message to be something that is compliant. 
See contributing.md for details or if short on time just change it to something like this:
`docs(contributing.md): explicit recommendation for avoiding global dependencies #585`
(I already updated the PR title to be the same)
I recommend amending the commit message and then force pushing so that there remains only a single commit with the correct message.

**Comment by zackvilla** [comment]
I hate to be _that guy_ but, how do I go about amending the commit message and force pushing?

**Comment by petermetz** [comment]
> I hate to be _that guy_ but, how do I go about amending the commit message and force pushing?

@zackvilla No worries, read through this and let me know if you still have questions: https://github.com/hyperledger/cactus/blob/main/CONTRIBUTING.md#git-know-how--reading-list

**Comment by zackvilla** [comment]
So I tried force pushing it, and it didn't seem to update anything here...

**Comment by petermetz** [comment]
> So I tried force pushing it, and it didn't seem to update anything here...

@zackvilla Do you have the amended commit message locally?
What does `git log` show? How about `git status` ?

**Comment by zackvilla** [comment]
Well this is the latest on the logs
git log
commit a8c10ffdf014af9dbb8c4799b0ef4ca7923fc50b (HEAD -> avoid-global-dependencicommit a8c10ffdf014af9dbb8c4799b0ef4ca7923fc50b (HEAD -> avoid-global-dependenci
es, origin/avoid-global-dependencies)
Author: Zachary Villanueva <Zachary.Villanueva@ibm.com>
Date:   Mon Jun 14 14:06:53 2021 -0500

    Documentation: Added warning to users about adding dependencies globally using npm in contributing.md
    
    Signed-off-by: Zachary Villanueva <Zachary.Villanueva@ibm.com>

**Comment by petermetz** [comment]
> Well this is the latest on the logs
> git log
> commit [a8c10ff](https://github.com/hyperledger/cactus/commit/a8c10ffdf014af9dbb8c4799b0ef4ca7923fc50b) (HEAD -> avoid-global-dependencicommit [a8c10ff](https://github.com/hyperledger/cactus/commit/a8c10ffdf014af9dbb8c4799b0ef4ca7923fc50b) (HEAD -> avoid-global-dependenci
> es, origin/avoid-global-dependencies)
> Author: Zachary Villanueva [Zachary.Villanueva@ibm.com](mailto:Zachary.Villanueva@ibm.com)
> Date: Mon Jun 14 14:06:53 2021 -0500
> 
> ```
> Documentation: Added warning to users about adding dependencies globally using npm in contributing.md
> 
> Signed-off-by: Zachary Villanueva <Zachary.Villanueva@ibm.com>
> ```

@zackvilla Right, you need to amend the message first and then force push.

```sh
git commit --amend --signoff

#
# then edit the commit message to match what I was recommending 
# or whatever else you feel like is better as long as it's compliant formatting wise

# finally force push
git push --force-with-lease
```

**Comment by zackvilla** [comment]
Ok that worked thank you so much, sorry for all the trouble. This is my first time committing to a big project like hyperledger.

**Comment by petermetz** [comment]
> Ok that worked thank you so much, sorry for all the trouble. This is my first time committing to a big project like hyperledger.

@zackvilla No worries, glad you decided to contribute to Cactus first, thank you very much!

**Review by takeutak — APPROVED** [review]

**Pull request merged**
