### PR TITLE
feat: add blockchain migration feature

### PR DESCRIPTION
**Pull request by RafaelAPB**
**This is work in progress - feedback is welcome**

This pull request introduces the blockchain migration feature, which is highly dependent on how the consortium management is implemented. The `approveMigration` method will allow a stakeholder to agree on the migration, via the consortium maangement plugin. 

Regarding the test, currently, it initializes a Besu blockchain migrator plugin. The idea is to submit transactions through Besu, capture the data they generate, and issue transactions against a target ledger (e.g., Quorum or Fabric). Finally, it should assert if the data migrated can be found at the target ledger.  

How to test this feature (similar instructions to PR #123):
-checkout this branch
-cd to the project root
-npm run configure -
-run the test at `packages/cactus-plugin-blockchain-migrator-besu/src/test/typescript/integration/plugin-ledger-blockchain-migrator-besu/data-migration/migrate-data-to-quorum.ts`

### CODE REVIEW

**Comment by petermetz** [comment]
@RafaelAPB set it as a 'draft' PR in line with it being WIP still. If you open a non-draft PR that should in general mean that it's ready for the maintainers to invest the time to review it from top to bottom. Not a big issue at all, just wanted to clarify. :-)

**Comment by petermetz** [comment]
@RafaelAPB Tried to give this a spin, but it won't build, see errors below:

```sh
@hyperledger/cactus-plugin-blockchain-migrator-besu: packages/cactus-plugin-blockchain-migrator-besu/src/main/typescript/plugin-ledger-blockchain-migrator-besu.ts:92:39
@hyperledger/cactus-plugin-blockchain-migrator-besu: ERROR: 92:39  no-shadowed-variable  Shadowed name: 'migrationDepth'
@hyperledger/cactus-plugin-blockchain-migrator-besu: ERROR: 93:39  no-shadowed-variable  Shadowed name: 'migrationType'
```

**Comment by kikoncuo** [comment]
This should only work natively and without resigning transactions for blockchains which have the same transaction arquitecture.
(Quorum, Besu, Geth, OpenEthereum, Nethermint and other open implementations based on the EVM)

That said, the networks may have to be configured in a specific way.
The chainID should be the same in all the configured networks which is not usually done.
This could potentially open users to replay attacks across different networks.

There might be a better approach migrating the contract and manually pushing a checkpoint data
Or asking all the agents to resign all their transactions

**Comment by RafaelAPB** [comment]
@kikoncuo thank you for the suggestions. That's an interesting path :) We can discuss further on the meetings

**Comment by kikoncuo** [comment]
Is this PR linked to an issue? if so, can you ping it on the main comment so we can track it better? (IE: Resolves #issueNumber)

**Comment by RafaelAPB** [comment]
@kikoncuo No, I don't think there's an issue on this.

**Review by petermetz — COMMENTED** [review]
@RafaelAPB Are you still working on this one?

**Comment by RafaelAPB** [comment]
@petermetz yes - sorry for the infinite delay, but still working on the paper/feature :)

**Comment by petermetz** [comment]
@RafaelAPB No worries, I'm just taking a pass on all the PRs to make sure we don't have dead ones hanging around. If you are still working on it it's cool to keep it open IMO.

**Pull request closed without merging**
