### PR TITLE
refactor(core-api): move PluginRegistry to core package

### LINKED ISSUE #380: refactor(core-api): move PluginRegistry to core package
### Description

The core API package should refrain from having implementation code in it so that it stays as true as possible to the name "API" in the old Java parlance where you would have `x-impl` and `x-api` artifacts containing the implementation and the API definitions/interfaces respectively.

### Acceptance Criteria
1. `PluginRegistry` class moved from the `cactus-core-api` package to the `cactus-core` package.
2. CI is passing.
3. References in documentation are updated accordingly as well.

cc: @takeutak @sfuji822 @jonathan-m-hamilton

### PR DESCRIPTION
**Pull request by petermetz**
## Commit to be reviewed:

```
commit 6c88f647baf6f5f70e47d2634697d47498e8bed4 (refactor/core-api/move-pluginregistry-to-core-package-380)
Author: Peter Somogyvari <peter.somogyvari@accenture.com>
Date:   Tue Dec 1 17:04:16 2020 -0800

    refactor(core-api): move PluginRegistry to core package
    
    Fixes #380
    
    Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

```

### CODE REVIEW

**Review by jonathan-m-hamilton — APPROVED** [review]
LGTM

**Review by takeutak — COMMENTED** [review]
The design of PluginRegistry depends to the architecture of Cactus, and this is now under the discussion in PR331,368. Therefore, please allow me to review this PR after PR331,368.

**Comment by petermetz** [comment]
> The design of PluginRegistry depends to the architecture of Cactus, and this is now under the discussion in PR331,368. Therefore, please allow me to review this PR after PR331,368.

@takeutak I think we could optimize our review pipeline/development processes in general to be a little more efficient if we didn't make code changes dependent on documentation changes happening first. 
With the risk of crossing into philosophy from software engineering: This goes back to my belief that as much as design is important, we are building something that we have never done before so it may be preferable to iterate fast and be willing to refactor often (while we still can, prior to the 1.0 launch) instead of attempting to get it right with up-front design that locks in the implementation. What do you think?

**Review by takeutak — APPROVED** [review]
LGTM

**Pull request merged**
