### PR TITLE
docs(readme.md): add Open in VSCode badge

### PR DESCRIPTION
**Pull request by shoebsd31**
Signed-off-by: shoeb <shoebsd31@gmail.com>

Added a vs code badge as described in this issue :  #1116

### CODE REVIEW

**Comment by petermetz** [comment]
@shoebsd31 Is this a duplicate of https://github.com/hyperledger/cactus/pull/1303

**Comment by shoebsd31** [comment]
> @shoebsd31 Is this a duplicate of https://github.com/hyperledger/cactus/pull/1303

Hi Peter,

I tries to squash the commits there were problem on my end. Can I delete the old PR and create a new PR?

**Comment by shoebsd31** [comment]
> @shoebsd31 Is this a duplicate of #1303

yes, I had to delete my old fork and create a new one. I closed to old PR. Unfortunately I couldn't delete it!

**Comment by petermetz** [comment]
> I tried to squash the commits there were problem on my end. Can I delete the old PR and create a new PR?


@shoebsd31 The answer to that generally is no because it forces a complete double review of everything in the PR which puts undue burden on the reviewers plus it also disappears all the reviews/comments that were put into the original PR.

> yes, I had to delete my old fork and create a new one.

Your fork is the same for the old and the new PR as well. Did you mean to say that you deleted your old branch and created a new one?
If yes, that's exactly what I was trying to avoid, if you invite me as a collaborator to your fork I can help with the git mechanics, just let me know and then we can fix up your original PR and close the duplicate one.

**Review by petermetz — CHANGES_REQUESTED** [review]
^^

**Comment by shoebsd31** [comment]
> > I tried to squash the commits there were problem on my end. Can I delete the old PR and create a new PR?
> 
> @shoebsd31 The answer to that generally is no because it forces a complete double review of everything in the PR which puts undue burden on the reviewers plus it also disappears all the reviews/comments that were put into the original PR.
> 
> > yes, I had to delete my old fork and create a new one.
> 
> Your fork is the same for the old and the new PR as well. Did you mean to say that you deleted your old branch and created a new one?
> If yes, that's exactly what I was trying to avoid, if you invite me as a collaborator to your fork I can help with the git mechanics, just let me know and then we can fix up your original PR and close the duplicate one.

I have sent you an invitation

**Review by petermetz — APPROVED** [review]

**Review by takeutak — APPROVED** [review]

**Pull request merged**
