### PR TITLE
test: jestify api client routing node to node test

### PR DESCRIPTION
**Pull request by Leeyoungone**
This test file required more refactoring because the `tap` tests were nested, however `jest` doesn't allow nested test cases

File Path: 
packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts

This is a PARTIAL resolution to issue #238

Signed-off-by: Youngone Lee <youngone.lee@accenture.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — APPROVED** [review]
@Leeyoungone LGTM, thank you!

**Comment by petermetz** [comment]
@Leeyoungone The PR description needs to be in the commit message as well, right now the commit message is mostly empty. Please copy & paste what you have in the PR description at the moment into the commit message and then force push with lease. (also don't forget to rebase onto upstream/main beforehand as usual)

**Review by petermetz — CHANGES_REQUESTED** [review]
@Leeyoungone Sorry , forgot to mark it as changes requested.

**Review by petermetz — APPROVED** [review]
> @petermetz All good! Thanks for letting me know :)

@Leeyoungone No worries, LGTM now, thank you!

**Pull request merged**
