### PR TITLE
refactor(cmd-socketio): fix strict flag warnings

### PR DESCRIPTION
**Pull request by outSH**
cmd-socketio-server will compile with global strict flag.

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

Part of https://github.com/hyperledger/cactus/issues/1671

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@outSH LGTM

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
@outSH Please resolve the conflicts and then we can merge.

**Comment by outSH** [comment]
@petermetz Done

**Pull request merged**
