### PR TITLE
fix: reset script from package.json does not work #1656

### PR DESCRIPTION
**Pull request by ruzell22**
fixes: #1656

Signed-off-by: ruzell22 <ruzell.vince.aquino@accenture.com>

### CODE REVIEW

**Comment by ruzell22** [comment]
@petermetz  , Upon reading further about yarn.lock, del-cli yarn.lock wasn’t needed and may cause problems. Letting yarn update the yarn.lock file is the better way in terms of updating dependencies.
(https://classic.yarnpkg.com/en/docs/yarn-lock/#toc-managed-by-yarn : # Managed by Yarn)
(https://stackoverflow.com/questions/60509429/is-it-a-good-idea-to-delete-yarn-lock-and-generate-it-again-by-running-yarn-inst)
(https://stackoverflow.com/questions/41126217/how-to-sync-yarn-lock-with-package-json)

Testing has also been done in terms of using “del-cli ‘**/node_modules’” and reinstalling + reconfiguring it.
yarn del-cli emptied node_modules (on the left side) 
image

yarn install --update-checksum --force checks yarn.lock and updates it necessarily and also installs node_modules together
(https://classic.yarnpkg.com/en/docs/cli/install/)
(https://stackoverflow.com/questions/41864099/how-do-i-force-yarn-to-reinstall-a-package)
(https://www.codegrepper.com/code-examples/shell/yarn+reinstall+all+packages)
image

yarn configure configured the package and outputs all lerna success 
image

Yarn reset is also reusable even after using yarn reset once unlike the other solutions I have tried.

**Review by petermetz — CHANGES_REQUESTED** [review]
> @petermetz  , Upon reading further about yarn.lock, del-cli yarn.lock wasn’t needed and may cause problems. Letting yarn update the yarn.lock file is the better way in terms of updating dependencies.
(https://classic.yarnpkg.com/en/docs/yarn-lock/#toc-managed-by-yarn : # Managed by Yarn)
(https://stackoverflow.com/questions/60509429/is-it-a-good-idea-to-delete-yarn-lock-and-generate-it-again-by-running-yarn-inst)
(https://stackoverflow.com/questions/41126217/how-to-sync-yarn-lock-with-package-json)

Testing has also been done in terms of using “del-cli ‘**/node_modules’” and reinstalling + reconfiguring it.
yarn del-cli emptied node_modules (on the left side) 
image

yarn install --update-checksum --force checks yarn.lock and updates it necessarily and also installs node_modules together
(https://classic.yarnpkg.com/en/docs/cli/install/)
(https://stackoverflow.com/questions/41864099/how-do-i-force-yarn-to-reinstall-a-package)
(https://www.codegrepper.com/code-examples/shell/yarn+reinstall+all+packages)
image

yarn configure configured the package and outputs all lerna success 
image

Yarn reset is also reusable even after using yarn reset once unlike the other solutions I have tried.  

@ruzell22 Sure thing, please also amend the commit message to contain this description of the solution and the reasoning behind it (screenshots can be omitted). That way if we ever choose to migrate away from github people can still look back in the git history itself and see why we were doing what we are. Other than that, LGTM and thank you again!

**Comment by ruzell22** [comment]
@petermetz I have updated the commit message. Thank you!
image

**Review by petermetz — CHANGES_REQUESTED** [review]
@ruzell22 Thank you very much, now the problem is that the commit message has lines longer than a 100 characters in the footer (see the commit lint CI check's logs for this below)

I recommend using rulers in VSCode while editing the commit message text so that you can always see where the 80/100/120 character lines are.

**Comment by ruzell22** [comment]
@petermetz I have now fixed the commit body not exceeding 100 characters per line. Thank you.

**Review by izuru0 — APPROVED** [review]
LGTM

**Pull request merged**
