### PR TITLE
chore(connector-go-eth): upgrade web3.js to recent version

### LINKED ISSUE #2088: chore(connector-go-eth): upgrade web3.js to recent version
`web3.js` package of `cactus-plugin-ledger-connector-go-ethereum-socketio` is old.
Upgrade it and adjust the connector code to work with the new version.

### PR DESCRIPTION
**Pull request by outSH**
- Upgrade web3 package used by go-ethereum-socketio connector from "0.20.7" to "1.8.1"
- Major cleanup and refactor of go-ethereum-socketio logic,
  without affecting the current functionalities.
- Add safety checking of method called in web3Eth and contract functions.
  Add tests to check if it works.
- Add websocket eth RPC support and some helper functions in openethereum-test-ledger.
- Expose WS RPC in geth-testnet, use this port in sample apps
  (required to monitor new blocks in updated web3.js)
- Change raw use of sendRawTransaction to sendSignedTransaction in sample apps
  in order to conform to new web3.js version.
- Add safeStringifyException to cactus-common that can be used by validators
  to sanitize response errors.
- Refactor socketio-based validators to use safeStringifyException.
- Adjust connector README files.
- Improve cleanup after running sample apps
- Fix discounted-cartrade sample ethereum transfer and checking

Closes #2088

Depends on #2053

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

------------

Please review only the last commit, the rest are dependencies that should be merged in separate PRs.

### CODE REVIEW

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by takeutak** [comment]
@petermetz @jagpreetsinghsasan  (cc: @izuru0)
Could you review this PR?

**Review by petermetz — APPROVED** [review]
@takeutak @outSH Sorry for the slow reviews again. LGTM

@outSH Please fix the conflicts and rebase so that prior to merging it's just the one commit remaining in the PR.

**Review by petermetz — CHANGES_REQUESTED** [review]
@outSH Please squash+rebase+fix the conflicts

**Comment by outSH** [comment]
> Please squash+rebase+fix the conflicts

@petermetz Done, I've also done some improvements in sample apps during testing.

Ready for merging

**Review by petermetz — APPROVED** [review]
> > Please squash+rebase+fix the conflicts

> @petermetz Done, I've also done some improvements in sample apps during testing.
> Ready for merging 

@outSH LGTM, thank you very much!

**Review by petermetz — APPROVED** [review]
> > Please squash+rebase+fix the conflicts

> @petermetz Done, I've also done some improvements in sample apps during testing.

> Ready for merging 

@outSH LGTM, thank you very much!

**Review by petermetz — CHANGES_REQUESTED** [review]
@outSH Please resolve the merge conflicts and then pass it back for review.

**Comment by outSH** [comment]
@petermetz Done, all should work

**Review by petermetz — APPROVED** [review]
@outSH LGTM, thank you!

**Pull request merged**
