### PR TITLE
docs: adding devcontainer docker file

### LINKED ISSUE #504: feat: add vs-code dev container json file
### Description
As a contributor I want to have convenience when setting up the project for development so that I'm more productive and more likely to actually contribute.

https://code.visualstudio.com/docs/remote/containers
https://code.visualstudio.com/docs/remote/devcontainerjson-reference

### TLDR on dev containers: 

VSCode can build the project inside the dev container so you can spare people the hassle of installing all of the build dependencies of the project on their machine (such as the JDK 8 which many people may run into trouble with especially if they already have a different version installed). With the dev container json file all one would need is VSCode and a functioning docker installation to be able work on Cactus code. @kikoncuo 

### Acceptance Criteria
1. .devcontainer.json file added in the project root
2. The image references by the added `.devcontainer.json` file in step 1) suports Docker in Docker or at least binding to the host's docker so that integration tests can be executed inside the container which themselves start other containers for ledger simulation.
3. Documentation added in the README.md that mentions the fact that we have this convenience feature available for those who do not wish to pollute their host machine with NodeJS/JDK installations for example.

cc: @sfuji822 @takeutak @hartm @jonathan-m-hamilton

### PR DESCRIPTION
**Pull request by TonyRowntree**
Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

**Added:**

- Devcontainer docker file

Resolve #504

### CODE REVIEW

**Comment by petermetz** [comment]
@TonyRowntree Is this the latest version of the code? I remember you updated the apk specific commands to apt instead but when I tried to run the container I got this:
Screenshot (120)

**Comment by TonyRowntree** [comment]
@petermetz I just checked, the code is correct. How was you trying to run the container?

**Comment by petermetz** [comment]
> @petermetz I just checked, the code is correct. How was you trying to run the container?

@TonyRowntree Oh, hopefully I just messed something up then!

Repro steps:

Windows 10 laptop:
1. Open empty VSCode
2. Clone your branch
3. Open the cloned repo with VSCode
4. Pop-up comes saying that it has a dev container and if I want to roll with that or not. 
5. Pick the option of "clone to volume" 
6. Follow-up prompt: Pick the option to clone it to a new volume
7. Then the screenshot happens

**Comment by TonyRowntree** [comment]
@petermetz I cloned to my Accenture machine and opened in container and mine compiled correctly (see below)
image

I assume the issue you was facing was to do with your laptop/connection, we can look into this at a later date.

**Comment by petermetz** [comment]
@TonyRowntree Works for me, we can investigate further if it pops up on other people's machine's as well, thanks for looking into it!

**Review by petermetz — APPROVED** [review]

**Review by takeutak — APPROVED** [review]

**Pull request merged**
