### PR TITLE
chore(deps): upgrade angular in examples/supply chain app

### LINKED ISSUE #2002: chore(deps): upgrade angular in examples/supply chain app
Basic security hygiene dictates that we upgrade our dependencies periodically to reduce risk.

Very similar to https://github.com/hyperledger/cactus/issues/1651

Depends on https://github.com/hyperledger/cactus/issues/1980

### PR DESCRIPTION
**Pull request by aldousalvarez**
Fixes #2002

Signed-off-by: aldousalvarez <aldousss.alvarez@gmail.com>

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@aldousalvarez LGTM, thank you!

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@aldousalvarez Unfortunately a merge conflict came in through one of the commits that got merged to main since this was approved. Please fix the conflict and then we should be good to go again.

**Comment by aldousalvarez** [comment]
Hello @petermetz fixed the merge conflict that you said. And now all checks have passed. Thank you

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
> Hello @petermetz fixed the merge conflict that you said. And now all checks have passed. Thank you 

@aldousalvarez Great, thanks. Please rebase onto `upstream/main` and then run `yarn` to make sure that the lock file is updated. Right now if you run `yarn` it produces a diff on the lock file.

**Comment by aldousalvarez** [comment]
@petermetz Already done. Thank you

**Comment by aldousalvarez** [comment]
Depends on #2096

**Review by petermetz — CHANGES_REQUESTED** [review]
@aldousalvarez Please fix the merge  conflicts and then LGTM.

**Comment by petermetz** [comment]
@aldousalvarez Please put the dependency declaration to the PR description next time. The bot doesn't scan the PR comments for it.

**Comment by aldousalvarez** [comment]
> @aldousalvarez Please fix the merge conflicts and then LGTM.

@petermetz Fixed the merge conflicts and now all checks have passed.



> @aldousalvarez Please put the dependency declaration to the PR description next time. The bot doesn't scan the PR comments for it.

My apologies on this one. Should I put it on the commit message with the fixes and signed-off-by?

**Comment by petermetz** [comment]
@aldousalvarez It still shows that the conflicts are there =>

```sh
This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
yarn.lock
```

**Comment by petermetz** [comment]
> My apologies on this one. Should I put it on the commit message with the fixes and signed-off-by?

@aldousalvarez Yes, that works best. I usually have the Fixes line and then right below it the depends on line

**Comment by aldousalvarez** [comment]
> @aldousalvarez It still shows that the conflicts are there =>
> 
> ```shell
> This branch has conflicts that must be resolved
>  to resolve conflicts before continuing.
> Conflicting files
> yarn.lock
> ```

my apologies on that one,

as of now all checks have passed and all conflicts have been resolved

**Review by petermetz — APPROVED** [review]
@aldousalvarez No worries, thanks for fixing it!
Other advice for the future (also not a big deal at all, just making sure you are aware) =>
when you make a change in response to a change request review (like the conflict resolution you just did) then you have to "pass the ball back" to the reviewer by re-requesting the review when you've addressed the change request.

**Pull request merged**
