### PR TITLE
feat(ipfs): ipfs-keychain implementation

### PR DESCRIPTION
**Pull request by TonyRowntree**
**Added**

- ipfs-keychain test case
- ipfs remove functionality

depends on #1007, #1032

### CODE REVIEW

**Comment by TonyRowntree** [comment]
@petermetz can you please review when you have some free time

**Review by petermetz — CHANGES_REQUESTED** [review]
@TonyRowntree Please 
1. squash *your* commits onto a single one (leave the ones that are coming from my PRs as-is). (otherwise it's going to be tough to review it because I have to pick each commit apart one by one)
2. Once you have squashed *your* commits together into a single one, please do a rebase onto my branch (the one with the IPFS object store plugin implementation)

Note that 2) might get difficult because I had to move the entire plugin implementation into a different directory altogether due to some change requests from other maintainers. If you need help with the git magic just ping me as usual.

**Comment by petermetz** [comment]
@TonyRowntree Let me know if you need help with the conflict resolution.

**Comment by petermetz** [comment]
Closing as inactive, we can reopen later as needed.

**Pull request closed without merging**
