### PR TITLE
fix: config-service validator throws warnings

### PR DESCRIPTION
**Pull request by m-courtin**
In multiple unit tests the config-validator of the config service throws
warnings as the validate function is finding properties on the instances
of plugins and the corresponding schema is NOT providing the related
schema definition required by the plugin interface.

Signed-off-by: Michael Courtin <michael.courtin@accenture.com>

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@m-courtin I agree with the direction, but the tests don't seem to be working (and it doesn't look like a flake either)

**Comment by m-courtin** [comment]
@petermetz: This PR is only about a fix of the schema validator so that during the UTs no further warnings are spamed into the logs regarding validation. The PR is not changing any test functionality

**Comment by m-courtin** [comment]
@petermetz: yes, totally agree. I will check why the tests are failing

**Comment by m-courtin** [comment]
@petermetz: Found the issue why the tests were failing and fixed it

**Review by petermetz — APPROVED** [review]
@m-courtin Thank you, LGTM! Fingers crossed that the flaky tests won't get in the way with the following executions.

**Review by takeutak — APPROVED** [review]

**Comment by m-courtin** [comment]
@petermetz: Test execution went fine :) Can you please merge the PR into main

**Comment by petermetz** [comment]
@m-courtin Yup, done now, thank you again ;-)

**Pull request merged**
