### PR TITLE
style: 2021-09-20 linter warnings batch 23/26

### PR DESCRIPTION
**Pull request by charellesandig**
fixes: #1372

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@charellesandig Thank you very much, LGTM!

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@charellesandig Please squash the commits into a single one, rebase onto main and then do a force push with lease. Right now the diff is split into two commits and we want it to be just the one when it gets merged onto main.

**Comment by charellesandig** [comment]
Hi @petermetz, I am done combining the 2 commits, thank you.

**Review by petermetz — APPROVED** [review]
@charellesandig LGTM, thank you very much!

**Pull request merged**
