### PR TITLE
style(test-tooling): fixed any type linter warns in quorum-test-ledger

### PR DESCRIPTION
**Pull request by alec-p-hong**
fixed 2 lint errors that were the any type error for Typescript and removed Node
Partial solution to #1375 

Signed-off-by: Alec Phong <alecphong@gmail.com>

### CODE REVIEW

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Comment by jagpreetsinghsasan** [comment]
Can we have a better commit message, something of this [sort](https://github.com/hyperledger/cactus/pull/1958/commits/028521580de4c444f6c49eafe1ab1e0f38509c2e)
This helps in understanding the changes done clearly from the commit message itself.

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@alec-p-hong +1 on Jagpreet's review and also my take saying the same thing basically: https://github.com/hyperledger/cactus/pull/2080#pullrequestreview-1041221189

**Review by petermetz — APPROVED** [review]
I changed the commit message, LGTM.

cc: @jagpreetsinghsasan @alec-p-hong

**Pull request merged**
