### PR TITLE
test: jestify invoke contract xdai test

### PR DESCRIPTION
**Pull request by awadhana**
Migrated test from Tap to Jest.

File Path:
packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/invoke-contract-xdai.test.ts

This is a PARTIAL resolution to issue #238

Signed-off-by: awadhana <awadhana0825@gmail.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@awadhana LGTM but before merging please make sure the PR description and the git commit are updated to not resolve the main jest issue.

**Comment by awadhana** [comment]
> @awadhana LGTM but before merging please make sure the PR description and the git commit are updated to not resolve the main jest issue.

Done :)

**Review by petermetz — APPROVED** [review]
@awadhana Thank you, LGTM!

**Comment by petermetz** [comment]
@awadhana There's a conflict on this one now. Please resolve and then we can merge!

**Comment by awadhana** [comment]
> @awadhana There's a conflict on this one now. Please resolve and then we can merge!

No problem

**Comment by petermetz** [comment]
@awadhana This one seems to have an issue with the ignore/include patterns again.

**Comment by petermetz** [comment]
@awadhana This one seems to have an issue with the ignore/include patterns again.

**Pull request merged**
