### PR TITLE
refactor(cmd-socketio): node config cleanup 

### PR DESCRIPTION
**Pull request by outSH**
- Cleanup and document default cmd-socketio config files.
- Fix sample apps configs (so that default is common, and changes are done only in usersetting).
- Store validator-specific files in more distinguishable folders.
- Use yarn add instead of link to simplify docker BLP debugging (debugger can't find linked modules).
- Store default validator keys in validator itself, not cmd-socketio, the keys will be stored and read from /etc/cactus, not the package sturcture. 
- Read supported BLP from config, remove hardcoded Ids from the code.

Closes: https://github.com/hyperledger/cactus/issues/1865

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

Depends on #1859
Depends on #1856

### CODE REVIEW

**Comment by outSH** [comment]
@izuru0 @takeutak @petermetz Please review (only the last commit)

**Review by petermetz — APPROVED** [review]
@outSH LGTM

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@outSH Please resolve the conflicts

**Comment by outSH** [comment]
@petermetz Done

**Review by petermetz — APPROVED** [review]
@outSH LGTM, thank you!

**Pull request merged**
