### PR TITLE
fix(example): fix README on examples/car-trade

### PR DESCRIPTION
**Pull request by takeutak**
related with Issue #590

Signed-off-by: Takuma TAKEUCHI <takeuchi.takuma@fujitsu.com>

### CODE REVIEW

**Review by kikoncuo — COMMENTED** [review]
NodeJS 12 makes sense, no need to specify the minor version, our specific version we are using is 12.13.0.
Ubuntu 18.04 makes sense due to our environments and tests.
We don't do our tests against CentOS, but if that's the version you are directly using we can keep it, otherwise we can just leave Ubuntu

**Comment by takeutak** [comment]
Thank you for your comment.
As for Node 12, I think "NodeJS v 12" is enough, but I added the subversion of Node.js that I tested as recommended version just in case.
I have tested this code on both Ubuntu 18.04 and CentOS and both work fine. Therefore, I think there is no need to modify the OS notation.
I think there is no problem here. Can you give me a comment if you have anything?

**Review by kikoncuo — APPROVED** [review]
No other comments looks good!

**Review by petermetz — APPROVED** [review]

**Comment by petermetz** [comment]
FYI: re-triggered the CI just now, looked like a fluke.

**Pull request merged**
