### PR TITLE
docs: add cross-references to BUILD.md and CONTRIBUTING.md #1394

### PR DESCRIPTION
**Pull request by Nancy8**
Document updates for issue #1394

### CODE REVIEW

**Comment by petermetz** [comment]
@Nancy8 Looks good, thank you! Now we just need to take care of the administrative requirements such as the DCO and the commit linting.
I recommend a commit message like this (you can edit the commit message with the --amend flag and then by force pushing)

> docs: add cross-references to BUILD.md and CONTRIBUTING.md #1394
>
> Fixes #1394

**Review by petermetz — APPROVED** [review]
@Nancy8 LGTM, thank you very much once again! If you need any help  with getting it over the finish line regarding the git mechanics, just let me know.

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@Nancy8 Sorry to bother again, now you just need to fix the DCO and then it should be fine, here are the details on how to do it: https://github.com/hyperledger/cactus/pull/1396/checks?check_run_id=3876134084

**Comment by petermetz** [comment]
In the meantime, closing due to inactivity, please feel free to reopen as needed and then we can pick it up again.

**Pull request closed without merging**
