### PR TITLE
refactor(sdk):renamed sdk package to api client

### LINKED ISSUE #314: refactor(sdk): rename sdk package to api-client
### Description
As a developer I want to be able to quickly scan the packages available in the git repo so that I can get a better understanding of the architecture in a shorter time.

Currently we have a package named `cactus-sdk` which is probably ambiguous with the project itself which we sometimes refer to as `an SDK of SDKs`. That ambiguity could cause rational minds to question our terminology (yet again) since if the whole project is `the` SDK then why do we have 10+ packages and only one of them called SDK.
Based on all this that we should rename the package from `@hyperledger/cactus-sdk` to `@hyperledger/cactus-api-client` which much better describes (narrower scope) what that package actually does.

### Acceptance Criteria
1. In the `package.json` file, the properties: name, main, browser, browserMinified, mainMinified properties are all updated
2. The references in all the other packages are also updated to import the new package instead of the old one (e.g. project must compile without issues
3. Documentation is updated where necessary (the readme.md file of the package needs a looksie for sure)

cc: @RafaelAPB @sfuji822 @jonathan-m-hamilton @takeutak

### PR DESCRIPTION
**Pull request by yash2189**
Fixes #314 

Previously there was a package named `cactus-sdk` which had ambiguity within the project since it was referred to as an SDK of SDK's. This PR renames the `cactus-sdk` to `cactus-api-client` and changes the documentation , files supporting the same.

What has been updated ?
1 . In the package.json file, the properties: name, main, browser, browserMinified, mainMinified properties are all updated
2. The references in all the other packages are also updated to import the new package instead of the old one
3. Documentation is updated  (`README.md`)

The changes for the updated directory can be found [here](https://github.com/yash2189/cactus/tree/fix%23314/packages/cactus-api-client)

### CODE REVIEW

**Comment by petermetz** [comment]
@yash2189 Thank you for the PR! Two things:
1. The build has to work, but you've got compilation errors in some of the code still.
2. The commit message is invalid, I think you are missing a space character after the colon.

Other than these (and with the assumption that the CI will pass) it looks good to me.

**Comment by yash2189** [comment]
@petermetz Thanks for the review. The errors a related to `npm linting` and `lerna` . Could you please tell me about this as I'm quite confused.

**Comment by petermetz** [comment]
> @petermetz Thanks for the review. The errors a related to `npm linting` and `lerna` . Could you please tell me about the errors as I'm quite confused.

@yash2189 I think you forgot to replace all the package imports from 'sdk' to 'api-client' in the code of the other packages that depend on `@hyperledger/cactus-sdk`.

See: https://travis-ci.org/github/hyperledger/cactus/jobs/738502564#L592

**Comment by petermetz** [comment]
@yash2189 Looks like now you added one too many spaces. The one on the left from the parentheses is tripping the commit message linter if I'm guessing it right.
`refactor (ask): renamed sdk package to api client ` should be `refactor(sdk): renamed sdk package to api client `
(also I assume the `ask` part is meant to be `sdk`

**Comment by yash2189** [comment]
> @yash2189 Looks like now you added one too many spaces. The one on the left from the parentheses is tripping the commit message linter if I'm guessing it right.
> `refactor (ask): renamed sdk package to api client ` should be `refactor(sdk): renamed sdk package to api client `
> (also I assume the `ask` part is meant to be `sdk`

sorry typo , I'm doing it again

**Comment by yash2189** [comment]
Hi @petermetz , All the 3 checks have been passed , I have made the changes.
Thanks.

**Comment by petermetz** [comment]
> Hi @petermetz , All the 3 checks have been passed , I have made the changes.
> Please tell me whether I need to squash the commits ?
> Thanks.

Awesome, thank you so much @yash2189 !
Yes, please do squash the commits into a single one and then it LGTM!

**Comment by yash2189** [comment]
@petermetz  Done! :)

**Review by petermetz — APPROVED** [review]
LGTM

**Review by takeutak — APPROVED** [review]
LGTM

**Pull request merged**
