### PR TITLE
refactor(electricity-trade): dockerize electricity-trade

### PR DESCRIPTION
**Pull request by outSH**
- Add new docker-compose and dockerfile for sample app setup.
- Add scripts for interacting with sample app, remove reduntant ones. 
- Use cmd-socketio as a module in electricity-trade. 
- Use pinned version when setting up sawtooth test network.
- Remove top level dist and etc dirs (not used anymore).
- Remove docker-compose files from validators - replace with plain docker instructions which are more appropriate for single container setup. Docker-compose is used by sample apps.

Closes: #1858
Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

### CODE REVIEW

**Comment by outSH** [comment]
@izuru0 @takeutak @petermetz - please review

**Review by petermetz — APPROVED** [review]
@outSH LGTM, thank you for cleaning things up a bit!

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by petermetz — COMMENTED** [review]
@outSH Please fix the merge conflicts when you get a chance, thank you!

**Comment by outSH** [comment]
@petermetz Done :)

**Pull request merged**
