### PR TITLE
refactor(core-api): keychain plugin get/set generic type parameters

### LINKED ISSUE #478: refactor(core-api): keychain plugin get/set generic type parameters
### Description

https://github.com/hyperledger/cactus/blob/acfa6380c774f6651cf256851ea6c02972474503/packages/cactus-core-api/src/main/typescript/plugin/keychain/i-plugin-keychain.ts

```typescript
  get<T>(key: string): Promise<T>;
  set<T>(key: string, value: T): Promise<void>;
```

Right now we have these methods as generic, but it may be better to lock it down to work on strings only since that's the most common (likely the only?) type we'll be dealing with as the plugin implementations are just passing information between calling code and the keychain backends anyway.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton

### PR DESCRIPTION
**Pull request by twiggins120**
refactor(core-api): keychain plugin get/set generics #1135 

Fixes #1135 
Signed-off-by: Tommesha Wiggins <tommesha.wiggins@accenture.com>

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@twiggins120 The change in `i-plugin-keychain.ts` looks good, now you just need to make sure that all the other packages also compile successfully (Highly recommend `npm run watch` )

Here's the first set of compiler errors (there's likely some more)
https://github.com/hyperledger/cactus/pull/1135/checks?check_run_id=3069683492#step:4:1140

cc: @ty-lazar

**Review by petermetz — CHANGES_REQUESTED** [review]
@twiggins120 The other thing that needs to be updated is the commit message to be compliant with the format. I recommend changing it to something like

```sh
refactor(core-api): keychain plugin get/set generics #1135

Fixes #1135 
```

(plus the sign-off line that gets automatically added by git)

cc: @ty-lazar

**Comment by petermetz** [comment]
@twiggins120 

```
> @hyperledger/cactus-plugin-ledger-connector-besu@0.5.0 tsc
> tsc --project ./tsconfig.json

Error: src/main/typescript/plugin-ledger-connector-besu.ts(559,53): error TS2558: Expected 0 type arguments, but got 1.
Error: src/main/typescript/plugin-ledger-connector-besu.ts(672,57): error TS2558: Expected 0 type arguments, but got 1.
Error: src/main/typescript/plugin-ledger-connector-besu.ts(677,26): error TS2339: Property 'abi' does not exist on type 'string'.
Error: src/main/typescript/plugin-ledger-connector-besu.ts(683,24): error TS2339: Property 'networks' does not exist on type 'string'.
```

**Comment by petermetz** [comment]
@twiggins120 Now there's some more places that the compiler has problems with so you have to take care of those as well (it's an incremental process because certain compilation errors will only show themselves once previous ones have been resolved - this is due to dependencies among the packages)

Hint from the CI logs (but you can obtain the same information if you build it locally)

```sh
Error: packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts(559,53): error TS2558: Expected 0 type arguments, but got 1.
Error: packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts(672,57): error TS2558: Expected 0 type arguments, but got 1.
Error: packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts(677,26): error TS2339: Property 'abi' does not exist on type 'string'.
Error: packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts(683,24): error TS2339: Property 'networks' does not exist on type 'string'.
2:55:04 PM - Project 'packages/cactus-plugin-ledger-connector-fabric/tsconfig.json' is out of date because output file 'packages/cactus-plugin-ledger-connector-fabric/dist/lib/main/typescript/chain-code-compiler.js' does not exist

2:55:04 PM - Building project '/home/runner/work/cactus/cactus/packages/cactus-plugin-ledger-connector-fabric/tsconfig.json'...

Error: packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts(832,55): error TS2558: Expected 0 type arguments, but got 1.
2:55:06 PM - Project 'packages/cactus-plugin-ledger-connector-quorum/tsconfig.json' is out of date because output file 'packages/cactus-plugin-ledger-connector-quorum/dist/lib/main/typescript/index.js' does not exist

2:55:06 PM - Building project '/home/runner/work/cactus/cactus/packages/cactus-plugin-ledger-connector-quorum/tsconfig.json'...

Error: packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts(453,53): error TS2558: Expected 0 type arguments, but got 1.
2:55:07 PM - Project 'packages/cactus-plugin-ledger-connector-xdai/tsconfig.json' is out of date because output file 'packages/cactus-plugin-ledger-connector-xdai/dist/lib/main/typescript/index.js' does not exist

2:55:07 PM - Building project '/home/runner/work/cactus/cactus/packages/cactus-plugin-ledger-connector-xdai/tsconfig.json'...

Error: packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts(463,53): error TS2558: Expected 0 type arguments, but got 1.
Error: packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts(587,57): error TS2558: Expected 0 type arguments, but got 1.
Error: packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts(592,26): error TS2339: Property 'abi' does not exist on type 'string'.
Error: packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts(598,24): error TS2339: Property 'networks' does not exist on type 'string'.
```

cc: @ty-lazar

**Comment by twiggins120** [comment]
@petermetz Will work on it. Thanks for the feedback.

**Comment by twiggins120** [comment]
Closing because of issue with the branch name.

**Pull request closed without merging**
