### PR TITLE
refactor: jest migration phase 1 - tap+jest coexistence

### PR DESCRIPTION
**Pull request by petermetz**
The idea here is that with this we can merge the current state of the
migration without having to finish it all in one go.

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

### CODE REVIEW

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by izuru0** [comment]
oops, approved a draft PR by mistake.
let me know when this PR became ready.

**Comment by petermetz** [comment]
@awadhana This is the PR I was talking about the other day, I'm hoping that the last failing tests are now fixed (we'll know in a couple of hours when the CI finishes)

**Comment by petermetz** [comment]
> oops, approved a draft PR by mistake. let me know when this PR became ready.

@izuru0 No worries. The PR is ready now (no longer a draft).
Tip for next time: You can dismiss your own review by re-requesting a review from yourself with the same icon in top right that you would normally re-request a review from others.

**Review by jonathan-m-hamilton — APPROVED** [review]
LGTM

**Pull request merged**
