### PR TITLE
docs: fix diagram typo in connector README files

### LINKED ISSUE #1613: docs: fix typos of diagraom instead of diagram
```sh
$ grep -ri 'diagraom' ./
./packages/cactus-plugin-ledger-connector-xdai/README.md:The above diagram shows the sequence diagraom of transact() method of the PluginLedgerConnectorXdai class. The caller to this function, which in reference to the above sequence diagram is API server, sends RunTransactionV1Request object as an argument to the transact() method. Based on the type of Web3SigningCredentialType, corresponsing responses are sent back to the caller.  
./packages/cactus-plugin-ledger-connector-fabric/README.md:The above diagram shows the sequence diagraom of transact() method of the PluginLedgerConnectorFabric class. The caller to this function, which in reference to the above sequence diagram is API server, sends RunTransactionRequest object as an argument to the transact() method. Based on the invocationType (FabricContractInvocationType.CALL, FabricCOntractInvocationType.SEND), corresponding responses are send back to the caller.
./packages/cactus-plugin-ledger-connector-fabric/README.md:The above diagram shows the sequence diagraom of enroll() method of the PluginLedgerConnectorFabric class. The caller to this function, which in reference to the above sequence diagram is API server, sends Signer object along with EnrollmentRequest as an argument to the enroll() method. Based on the singerType (FabricSigningCredentialType.X509, FabricSigningCredentialType.VaultX509, FabricSigningCredentialType.WsX509), corresponding identity is enrolled and stored inside keychain. 
./packages/cactus-plugin-ledger-connector-besu/README.md:The above diagram shows the sequence diagraom of transact() method of the PluginLedgerConnectorBesu class. The caller to this function, which in reference to the above sequence diagram is API server, sends RunTransactionRequest object as an argument to the transact() method. Based on the type of Web3SigningCredentialType, corresponsing responses are sent back to the caller.  
```

### PR DESCRIPTION
**Pull request by epartakki**
Fixes #1613

Signed-off-by: Eleni Partakki <elenipartakki@gmail.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@epartakki We are making progress, but not there just yet. It seems like your email address is not the right one, meaning that you put one down that is not on your GitHub profile.

If you look at the "Summary" section of the DCO check error page, then you can see there that it was expecting a different email address for the `Signed off by ...` line:

https://github.com/hyperledger/cactus/pull/1955/checks?check_run_id=5758861088

Screenshot from 2022-03-30 14-46-22

**Comment by epartakki** [comment]
Ah! My bad! One moment!

**Comment by petermetz** [comment]
> Ah! My bad! One moment!

@epartakki No worries at all, this almost always stumps people who are coming in as first time contributors. 
We are getting closer, but it still fails (the DCO check on the bottom has a red cross next to it). I think the email is now good, but for some reason it insists on your name being your GitHub username in the sign-off message instead of your official human name. No idea why it does that. I was going to guess that it's because your profile on GH might not have your full name but it does so go figure.
@ryjones Do you happen to know how exactly it determines the valid sign-off name for a given GH user?

**Review by petermetz — CHANGES_REQUESTED** [review]
^^ see above

**Comment by petermetz** [comment]
> @petermetz Thank you for the clarification! How can I squash the commits into 1?

@epartakki My pleasure! You can do that with an interactive rebase and then pick squash. The details of this are explained in this article for example, but if you run into trouble just let me know: https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by epartakki** [comment]
> https://www.internalpointers.com/post/squash-commits-into-one-git

When I do `git log`, I see commits from other people, and only one commit from myself, so I am unsure of how to proceed with this.

**Comment by petermetz** [comment]
> > https://www.internalpointers.com/post/squash-commits-into-one-git
> 
> When I do `git log`, I see commits from other people, and only one commit from myself, so I am unsure of how to proceed with this.

@epartakki I'm guessing if you do a `git status` it shows that there is "divergence" between your local and remote branches because here on the PR page of GitHub it shows that there are 2 commits on your remote branch.
What you likely need is just a `git push --force-with-lease` to eliminate the divergence.

**Review by petermetz — APPROVED** [review]
@epartakki LGTM, thank you!

**Comment by ryjones** [comment]
> @ryjones Do you happen to know how exactly it determines the valid sign-off name for a given GH user?

I do not, @petermetz

**Pull request merged**
