### PR TITLE
test: jestify cactus-test-plugin-htlc-eth-besu/withdraw-endpoint-invalid

### PR DESCRIPTION
**Pull request by awadhana**
Migrated test from Tap to Jest

File Path:
packages/cactus-test-plugin-htlc-eth-besu/src/test/
typescript/integration/plugin-htlc-eth-besu/
withdraw-endpoint-invalid.test.ts

This is a PARTIAL resolution to issue hyperledger#238

Signed-off-by: awadhana <awadhana2021@gmail.com>

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@awadhana LGTM

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
@awadhana Looks like something is off with the config files/ignore/include patterns on this one:

```sh
2022-02-18T16:07:09.3493946Z Unable to find Jest's global expect.
2022-02-18T16:07:09.3494896Z Please check you have added jest-extended correctly to your jest configuration.
2022-02-18T16:07:09.3496477Z See https://github.com/jest-community/jest-extended#setup for help.
2022-02-18T16:07:19.3993589Z /home/runner/work/cactus/cactus/packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts:2
2022-02-18T16:07:19.3994217Z import "jest-extended";
2022-02-18T16:07:19.3997183Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ^
2022-02-18T16:07:19.4059288Z ReferenceError: describe is not defined
2022-02-18T16:07:19.4060454Z     at Object.<anonymous> (/home/runner/work/cactus/cactus/packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts:2:2157)
2022-02-18T16:07:19.4061032Z     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2022-02-18T16:07:19.4062147Z     at Module.replacementCompile (/home/runner/work/cactus/cactus/node_modules/append-transform/index.js:60:13)
2022-02-18T16:07:19.4062787Z     at Module.m._compile (/home/runner/work/cactus/cactus/node_modules/ts-node/src/index.ts:1311:23)
2022-02-18T16:07:19.4063386Z     at module.exports (/home/runner/work/cactus/cactus/node_modules/default-require-extensions/js.js:7:9)
2022-02-18T16:07:19.4064178Z     at /home/runner/work/cactus/cactus/node_modules/append-transform/index.js:64:4
2022-02-18T16:07:19.4065119Z     at require.extensions.<computed> (/home/runner/work/cactus/cactus/node_modules/ts-node/src/index.ts:1314:12)
2022-02-18T16:07:19.4065707Z     at Object.<anonymous> (/home/runner/work/cactus/cactus/node_modules/append-transform/index.js:64:4)
2022-02-18T16:07:19.4066106Z     at Module.load (internal/modules/cjs/loader.js:937:32)
2022-02-18T16:07:19.4066467Z     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2022-02-18T16:07:19.4067054Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
2022-02-18T16:07:19.4067492Z     at internal/main/run_main_module.js:17:47
2022-02-18T16:07:19.4484223Z # Subtest: ./packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts
2022-02-18T16:07:19.4485157Z     1..0 # no tests found
2022-02-18T16:07:19.4593461Z not ok 118 - ./packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts # time=17962.942ms
2022-02-18T16:07:19.4594344Z   ---
2022-02-18T16:07:19.4596264Z   env:
2022-02-18T16:07:19.4597949Z     TS_NODE_COMPILER_OPTIONS: "{}"
2022-02-18T16:07:19.4600882Z   file: ./packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts
2022-02-18T16:07:19.4601774Z   timeout: 900000
2022-02-18T16:07:19.4602080Z   command: /opt/hostedtoolcache/node/14.17.6/x64/bin/node
2022-02-18T16:07:19.4602330Z   args:
2022-02-18T16:07:19.4602535Z     - -r
2022-02-18T16:07:19.4603051Z     - /home/runner/work/cactus/cactus/node_modules/ts-node/register/index.js
2022-02-18T16:07:19.4603442Z     - --max-old-space-size=4096
2022-02-18T16:07:19.4604190Z     - ./packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts
2022-02-18T16:07:19.4604682Z   stdio:
2022-02-18T16:07:19.4606364Z     - 0
2022-02-18T16:07:19.4606584Z     - pipe
2022-02-18T16:07:19.4607430Z     - 2
2022-02-18T16:07:19.4607681Z   cwd: /home/runner/work/cactus/cactus
2022-02-18T16:07:19.4607911Z   exitCode: 1
2022-02-18T16:07:19.4608079Z   ...
2022-02-18T16:07:19.4720056Z 
2022-02-18T16:07:19.4725060Z Bail out! ./packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts
2022-02-18T16:07:27.3097170Z Unable to find Jest's global expect.
2022-02-18T16:07:27.3098363Z Please check you have added jest-extended correctly to your jest configuration.
2022-02-18T16:07:27.3193494Z See https://github.com/jest-community/jest-extended#setup for help.
2022-02-18T16:07:37.4712287Z /home/runner/work/cactus/cactus/packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint-invalid.test.ts:2
2022-02-18T16:07:37.4713241Z import type { AddressInfo } from "net";
2022-02-18T16:07:37.4715705Z                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ^
2022-02-18T16:07:37.4718086Z ReferenceError: describe is not defined
2022-02-18T16:07:37.4719326Z     at Object.<anonymous> (/home/runner/work/cactus/cactus/packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint-invalid.test.ts:2:2096)
2022-02-18T16:07:37.4719951Z     at Module._compile (internal/modules/cjs/loader.js:1072:14)
2022-02-18T16:07:37.4720542Z     at Module.replacementCompile (/home/runner/work/cactus/cactus/node_modules/append-transform/index.js:60:13)
2022-02-18T16:07:37.4721185Z     at Module.m._compile (/home/runner/work/cactus/cactus/node_modules/ts-node/src/index.ts:1311:23)
2022-02-18T16:07:37.4721807Z     at module.exports (/home/runner/work/cactus/cactus/node_modules/default-require-extensions/js.js:7:9)
2022-02-18T16:07:37.4722386Z     at /home/runner/work/cactus/cactus/node_modules/append-transform/index.js:64:4
2022-02-18T16:07:37.4723297Z     at require.extensions.<computed> (/home/runner/work/cactus/cactus/node_modules/ts-node/src/index.ts:1314:12)
2022-02-18T16:07:37.4723935Z     at Object.<anonymous> (/home/runner/work/cactus/cactus/node_modules/append-transform/index.js:64:4)
2022-02-18T16:07:37.4724328Z     at Module.load (internal/modules/cjs/loader.js:937:32)
2022-02-18T16:07:37.4724714Z     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2022-02-18T16:07:37.4725141Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
2022-02-18T16:07:37.4725518Z     at internal/main/run_main_module.js:17:47
```

**Review by petermetz — CHANGES_REQUESTED** [review]
^^ @awadhana Sorry, forgot to put it into 'change requested' state.

**Comment by petermetz** [comment]
Hmm, seems like in the meantime this got migrated on another PR/branch so I'll close this one.

The other commit that did the migration for reference: https://github.com/hyperledger/cactus/tree/70b2f113e3ff0d9e3ff85c0bafa5491f45ae6285

**Pull request closed without merging**
