### PR TITLE
test: jestify v2141 deploy contract from json

### PR DESCRIPTION
**Pull request by awadhana**
Migrated test from Tap to Jest.

File Path:
packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json.test.ts

This is a PARTIAL resolution to issue #238

Signed-off-by: awadhana awadhana0825@gmail.com

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@awadhana Please squash the commits in a way that there's two commits left in the PR:
1. is the commit from the coexistence branch
2. the commit that is your PR on top of the commit from 1)

Also: I just pushed some changes to the co-existence branch so it's recommended to rebase onto it as well (no big changes so there shouldn't be any crazy conflicts in it)

---

Quick update: I just merged the co-existence branch, CI passing fine now, so at this point you can rebase onto upstream/main and have just a single commit on this PR (and the diff should shrink down to just a few files which will be great for everyone involved :-) )

**Comment by awadhana** [comment]
> @awadhana Please squash the commits in a way that there's two commits left in the PR:
> 
> 1. is the commit from the coexistence branch
> 2. the commit that is your PR on top of the commit from 1)
> 
> Also: I just pushed some changes to the co-existence branch so it's recommended to rebase onto it as well (no big changes so there shouldn't be any crazy conflicts in it)
> 
> Quick update: I just merged the co-existence branch, CI passing fine now, so at this point you can rebase onto upstream/main and have just a single commit on this PR (and the diff should shrink down to just a few files which will be great for everyone involved :-) )

Done :)

**Comment by petermetz** [comment]
@awadhana The `resolves #238` would make it so that when this is merged it will automatically close down that issue (which we don't want just yet because that's the main issue for all the tests combined. You might need to do two things:
1. Update the PR description (and the git commit message in sync)
2. Manually un-link the issue from the PR on the left hand side in the linked issues section.

**Review by petermetz — CHANGES_REQUESTED** [review]
@awadhana Thank you, LGTM just please make sure to update the issue linking so that it doesn't auto-close the main Jest issue and then this is ready for merging IMO

**Review by petermetz — APPROVED** [review]
@awadhana Thank you, LGTM

**Review by takeutak — APPROVED** [review]

**Pull request merged**
