### PR TITLE
style: 2021-09-20 linter warnings batch 21/26

### PR DESCRIPTION
**Pull request by ruzell22**
fixes: #1370

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@ruzell22 You can get away with this one line of change instead of the diff that you have right now. Doing the cast like this would be beneficial because it's still just a cast regardless, but it makes life easier for some other PRs that are queued up to make a change on this file as well).

```typescript
const fields = e.response.data.map((param: { path: string }) =>
```

**Comment by ruzell22** [comment]
@petermetz I have applied your suggested one line change and updated the pull request. Thank you.

**Review by petermetz — APPROVED** [review]
@ruzell22 Great, thank you for making the changes, LGTM!

**Review by petermetz — CHANGES_REQUESTED** [review]
@ruzell22 Oops, one more thing, sorry. Please squash+rebase onto upstream/main + force push with lease so that it's nice and tidy with a single commit when it gets merged onto `main`.
Right now the PR has 10 commits and ideally it would only have 1 (plus any GH merge commits that GH will know how to disappear automatically, but not the ones that you made manually)

**Comment by ruzell22** [comment]
@petermetz I have successfully squash and rebase + force push with lease with only 1 commit left reflected here. Thank you

**Comment by petermetz** [comment]
> @petermetz I have successfully squash and rebase + force push with lease with only 1 commit left reflected here. Thank you

@ruzell22 When you are doing the rebase you need to make sure that you accept changes from the main branch as well as from your own so that the diff between main and your branch remains equal to only the things you wanted to change.
Right now you have almost 200 files changed on your branch which makes me think that you are reverting the commits that have been added to main since you opened the PR.
If you need more help just let me know and we can figure it out together.

**Comment by ruzell22** [comment]
@petermetz it took me a few tries but I have fixed the squashing and force pushing with lease now to 1 file changed. Also, updated the code as well to its intended changes.

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
> @petermetz it took me a few tries but I have fixed the squashing and force pushing with lease now to 1 file changed. Also, updated the code as well to its intended changes.

@ruzell22 Great, thank you very much! One last nit:

The commit message right now is

```sh
style: 2021-09-20 linter warnings batch 21/26
Signed-off-by: ruzell22 <ruzell.vince.aquino@accenture.com>

style: 2021-09-20 linter warnings batch 21/26

Signed-off-by: ruzell22 <ruzell.vince.aquino@accenture.com>

style: 2021-09-20 linter warnings batch 21/26

Signed-off-by: ruzell22 <ruzell.vince.aquino@accenture.com>

style: 2021-09-20 linter warnings batch 21/26

Signed-off-by: ruzell22 <ruzell.vince.aquino@accenture.com>
```

but it would be great if you could tidy that up a bit and also make sure to mention the issue number that is being fixed, e.g. something like this below.
As usual, if you need help with the commit message amend, just let me know.
The `Fixes #1370` part in the commit message is important because that way the git log retains the information not just GitHub's internal database that stores the PR descriptions.

```sh
style: 2021-09-20 linter warnings batch 21/26

Fixes #1370

Signed-off-by: ruzell22 <ruzell.vince.aquino@accenture.com>
```

**Comment by petermetz** [comment]
@ruzell22 Also one more tip: when you are done with making changes, it helps if you mark it as ready for review (again) with the re-request review button next to my name. That puts the PR on my radar faster (I have a dedicated filter that lists all the PRs that I've been requested to provide reviews for and right now this PR would not show up on that list - the only reason why I'm here anyway typing this is because you tagged me in your comment and so I get around to answering it anyway, but sometimes I only have time to check the filter of PRs that need review)

**Comment by ruzell22** [comment]
@petermetz thanks for the tip about the re-review button. Also, I have cleaned up the commit message and body.

**Review by petermetz — APPROVED** [review]
@ruzell22 You are welcome and thanks for the PR, LGTM

**Pull request merged**
