### PR TITLE
chore(release): publish v0.4.0

### PR DESCRIPTION
**Pull request by petermetz**

### CODE REVIEW

**Comment by takeutak** [comment]
With the release of version 0.4, we would like to feature the features mentioned in this issue #667 . I would like to release it after completing the integration tests mentioned here. I would like to hear the opinions of Peter and other contributors at the Contributors conference and so on.

**Comment by petermetz** [comment]
> Thank you for thinking about version 0.4. I appreciate it.
> With the release of version 0.4, we would like to feature the features mentioned in this issue #667 . I would like to release it after completing the integration tests mentioned here. I would like to hear the opinions of @petermetz and other contributors at the Contributors conference and so on.

We agreed in the maintainer's call today to issue the release on the 31st of March, 2021.

**Review by sfuji822 — APPROVED** [review]
Great job. LGTM

**Review by takeutak — APPROVED** [review]

**Comment by petermetz** [comment]
@sfuji822 @takeutak Cheers, glad we could make it in time! I'll issue the release ASAP.

**Review by kikoncuo — APPROVED** [review]

**Pull request merged**
