### PR TITLE
feat(api-server): TLS, mTLS support

### PR DESCRIPTION
**Pull request by petermetz**
This is not really something that we expect to be used in
production due to the prevalence of load balancers and
reverse proxies in most production scale web application
deployments, but it is a must have for testing and also
for us to be able to claim that we take the secure by
default design principle seriously.

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

### CODE REVIEW

**Comment by petermetz** [comment]
> but I would like to implement this with external server such as nginx.

@sfuji822 This change does not restrict you from doing that in any way. It's all opt-in by way of configuration flags that can turn TLS/mTLS on and off.

**Comment by petermetz** [comment]
FYI: Did a rebase to resolve newly arisen conflicts after the other PRs got merged (then force pushed to keep the branch/PR tidy)

**Comment by takeutak** [comment]
LGTM.  We may fix later as another item in terms of the above discussion points.

**Comment by petermetz** [comment]
> OK. We may fix it later. I will create a new issue as action item to myself.

> LGTM. We may fix later as another item in terms of the above discussion points.

Thank you. Let's continue that discussion in #220 then.

**Pull request merged**
