### PR TITLE
chore(release): publish v1.0.0-rc.0

### PR DESCRIPTION
**Pull request by petermetz**

### CODE REVIEW

**Review by kikoncuo — APPROVED** [review]

**Comment by takeutak** [comment]
Thank you for posting. Sorry for my late reply.
As I said at Contributor's meeting, I think we need to consider the item list for V1.
I am very sorry, but I will have a holiday until next week and it is difficult for me to respond, but I plan to prepare a countermeasure plan as soon as possible after that. Could you wait for a moment, please?

**Comment by petermetz** [comment]
> As I said at Contributor's meeting, I think we need to consider the item list for V1.

@takeutak 

> @petermetz Thank you for posting. Sorry for my late reply.

It's okay.

> As I said at Contributor's meeting, I think we need to consider the item list for V1.

Great. I said the same thing months ago and opened pull requests to try and move the discussion along. 
Could you please include your proposed items here in the road map and then list the ones you deem necessary for V1?

> I am very sorry, but I will have a holiday until next week and it is difficult for me to respond, but I plan to prepare a countermeasure plan as soon as possible after that. Could you wait for a moment, please?

No worries, enjoy your holiday, we can resume the conversation when you are back.

**Comment by petermetz** [comment]
@takeutak +1

**Comment by takeutak** [comment]
@petermetz Sorry for late replying on GitHub PR comments.  As I mentioned on #716 and previous contributors' meetings, the checkpoints for V1-RC must be fixed and achieved before releasing V1-RC.

**Pull request closed without merging**
