### PR TITLE
fix(lint) escaping double quotes to prevent error on windows

### PR DESCRIPTION
**Pull request by travis-payne**
Primary Change:

- Small change in package.json to fix errors when the ESLint script gets ran.

Resolve #775

### CODE REVIEW

**Comment by kikoncuo** [comment]
This fixes windows compatibility when trying to lint the code in windows and all scripts which use lint

**Comment by kikoncuo** [comment]
@travis-payne please change the title to match format from other PRs, and congrats on your first PR!

**Review by kikoncuo — CHANGES_REQUESTED** [review]
Change the title of the PR to match the same format as other PRs.

The rest LGTM! good first PR congrats!!

**Review by petermetz — APPROVED** [review]

**Comment by petermetz** [comment]
@sfuji822 @takeutak Kindly requesting that you review or follow-up on the review discussion within this pull request (whichever is applicable). Thank you very much in advance.

**Review by petermetz — APPROVED** [review]

**Comment by travis-payne** [comment]
@sfuji822 @takeutak 

Hi guys, would you be able to take a quick review of this? It's quite a small change.

**Pull request closed without merging**
