### PR TITLE
chore: release automation

### LINKED ISSUE #45: chore: continuous deployment and releases
The release process should be as automated as possible.
One manual chore of issuing a release right now is to write a change log, but that can be automated with tooling and a strict convention on commit messages that allows the tooling to automatically gather up meaningful changes from the commit log and dump them in a designated file (`CHANGELOG.md`) 

https://github.com/conventional-changelog/conventional-changelog

https://github.com/commitizen/cz-cli

### PR DESCRIPTION
**Pull request by petermetz**
Fixes #45 

Depends on #308 => meaning that #308 must be merged first prior to this getting merged.

### CODE REVIEW

**Review by jonathan-m-hamilton — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
Clarification for reviewers: this is the only commit in this PR that needs the review

```
chore: release automation …
caea7b4
Adds npm scripts to issue canary and primary (patch,
minor, major) releases through the conventional
commits feature of lerna.

One-time commands to run once ready for the 0.2.0 release (these
are different from the otherwise workable defaults due to the
initial release being issued in the monorepo):

npm run lerna-publish-canary -- --force-publish

npx lerna publish 0.2.0 --conventional-commits --sign-git-commit --sign-git-tag

After this initial release of 0.2.0 the npm scripts
themselves will work as expected without the need
to customize the commands as presented above.

Fixes #45

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>
```

**Review by takeutak — APPROVED** [review]
LGTM, as the range of this PR <https://github.com/hyperledger/cactus/pull/338/commits/4c4036bc5a7eca569ab638f9cd1b57f8a894b5bd>

**Comment by takeutak** [comment]
As I said in other pull-requests, I only review within this commit <https://github.com/hyperledger/cactus/pull/338/commits/4c4036bc5a7eca569ab638f9cd1b57f8a894b5bd>.  When merging this PR, please make sure that other commits are not merged by mistake.

**Pull request merged**
