### PR TITLE
docs(readme): add build script decision tree

### PR DESCRIPTION
**Pull request by petermetz**
## Dependencies

Depends on #656 

## Commit to be reviewed

Also: add links to the BUILD.md and CONTRIBUTING.md files.
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

### CODE REVIEW

**Review by jonathan-m-hamilton — DISMISSED** [review]
LGTM

**Comment by petermetz** [comment]
@sfuji822 @takeutak Pushed changes according to the change requests.

**Review by jonathan-m-hamilton — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
@sfuji822 @takeutak Kindly requesting that you review this pull request. Thank you very much in advance.

**Comment by petermetz** [comment]
@sfuji822 @takeutak Kindly requesting that you review this pull request. Thank you very much in advance.

**Comment by takeutak** [comment]
@petermetz Sorry for late replying. I think there is no problem with the contents of the PR, but could you put the original file that can be modified of the png image in the subdirectory if you have it? I also plan to add LedgerPlugin desicison tree later.

**Comment by petermetz** [comment]
> build-script-decision-tree-2021-03-06

@takeutak Done. 
This already covers the ledger plugins as-is though so no need to modify AFAICT.

**Review by takeutak — APPROVED** [review]

**Pull request merged**
