### PR TITLE
fix(yarn-npm-replace): replace npm with yarn in Dockerfile

### LINKED ISSUE #1237: proxy server issue regarding npm use
**Describe the bug**

npm won't refer http_proxy environment variable while dockernizing. It can be solved by replacing with yarn.

**To Reproduce**

Even when --build-arg http_proxy=<proxy_url> is given, npm will not refer the environment variable.
The docker build process will fail when internet access is through a proxy server.
That causes some issues when the code builder is behind a firewall or the case 'apk update' failed on direct connection.
This problems is observed at:
 - packages/cactus-cmd-api-server/Dockerfile
 - packages/cactus-plugin-ledger-connector-besu/Dockerfile
 - packages/cactus-plugin-ledger-connector-fabric/Dockerfile

**Expected behavior**

The image build will succeed when the build arg 'http_proxy' is given.

**Operating system name, version, build:**

CentOS 7 with docker 20.10.8

### PR DESCRIPTION
**Pull request by sfuji822**
Improve Dockernization by replacement of npm with yarn.
This PR is a fix regarding Issue #1237
Signed-off-by: Shingo Fujimoto <shingo_fujimoto@fujitsu.com>

Update by Peter:
(this is the syntax that GitHub parses to link the issue and the PR together for automatic issue closure once the PR is merged)
Fixes #1237

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
LGTM

**Review by petermetz — APPROVED** [review]
LGTM (previous one was mis-click)

**Review by takeutak — APPROVED** [review]

**Comment by takeutak** [comment]
@petermetz Conflicts happen in the following files. Could you resolve these conflicts?
- packages/cactus-cmd-api-server/Dockerfile
- packages/cactus-plugin-ledger-connector-besu/Dockerfile

Conflicts logs are described as the following (You can check these logs on the above button of "Resolve conflicts"):

```
// packages/cactus-cmd-api-server/Dockerfile

<<<<<<< yarn
RUN yarn add @elenaizaguirre/cactus-cmd-api-server@${NPM_PKG_VERSION}
=======
RUN npm install @hyperledger/cactus-cmd-api-server@${NPM_PKG_VERSION} --production
>>>>>>> main
```

```
// packages/cactus-plugin-ledger-connector-besu/Dockerfile

<<<<<<< yarn
RUN yarn add @hyperledger/cactus-plugin-ledger-connector-besu@${NPM_PKG_VERSION} --production
=======
RUN npm install @hyperledger/cactus-plugin-ledger-connector-besu@${NPM_PKG_VERSION} --production
>>>>>>> main

```

**Comment by petermetz** [comment]
@takeutak Sure thing.

**Pull request merged**
