### PR TITLE
feat(core-api): discontinue dedicated HTTP listeners for web service plugins

### LINKED ISSUE #358: refactor: discontinue dedicated HTTP listeners (ExpressJS apps) for web service plugins
### Description

Originally we implemented this feature to provide the possibility for deployments to run plugins isolated on separate web domains/network hosts, but with today's code the latter can also be achieved by running multiple API servers which makes the dedicated HTTP listeners of plugins a redundant feature which also throws a wrench into the consortium definition powered routing within nodes.

Added benefit: Make it less confusing to implement plugins.

--- 

Examples of the code that is being talked about in this issue:

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts#L68

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts#L101

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts#L58

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts#L73
---

These shutdown methods on plugin classes could be deleted since this change would place the concern of HTTP listeners back completely to the control of the API server:
https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts#L45

--- 

Also could get rid of these from the common interface definition for web service plugins:

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts#L9

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts#L10

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts#L20

https://github.com/hyperledger/cactus/blob/3f0d86d2d7a95fce63bae2635466644e461d5f3e/packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts#L23

### Acceptance Criteria
1. Redundant code is removed
2. Updated the common web service plugin interface
3. Code compiles, tests are passing. Where applicable test cases were updated so that the HTTP layer isolation is demonstrated via separate instances of API servers rather than plugins running their dedicated listeners. 

cc: @sfuji822 @takeutak @jonathan-m-hamilton

### PR DESCRIPTION
**Pull request by TonyRowntree**
Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

Draft PR will amend when changed

resolves #358

### CODE REVIEW

**Comment by petermetz** [comment]
@TonyRowntree Very sorry, I just realized that we do need the shutdown method on the plugins because there may be other resources that the plugin needs to deallocate/destroy when the API server is shutting down (like disconnecting event handlers, web sockets or whatever else we start using). Could you put those back? Including the part where the API server calls them as part of it's own shutdown. Most of them will be empty, same way the async initializers are (for now).

**Review by petermetz — CHANGES_REQUESTED** [review]
@Leeyoungone Still 21 hits when I search for `"gethttpserver()"`

**Comment by Leeyoungone** [comment]
@petermetz oof, this is embarrassing. I think I finally understand the issue fully. So sorry about that earlier!!

**Review by petermetz — CHANGES_REQUESTED** [review]
@Leeyoungone Just these 4 files remaining now:

image

**Comment by Leeyoungone** [comment]
Sorry!! I think I got it now :)

**Review by petermetz — APPROVED** [review]
@Leeyoungone No worries, thank you for keeping at it! Admin chore nit-pick: if it's ready for re-view please hit the "re-request review" button too (I did it just now, but sometimes I only have time to filter on PRs that are in state of "awaiting review")

**Review by takeutak — APPROVED** [review]

**Comment by Leeyoungone** [comment]
@petermetz Thank you for looking at this PR, I can't seem to click the re-request review because it's not my original PR :(( However, I will keep that in mind next time when I can

**Comment by petermetz** [comment]
@Leeyoungone Aaaa, facepalm, sorry I forgot we already had this conversation. :-)

**Comment by Leeyoungone** [comment]
All good!! Don't worry about it :)

**Pull request merged**
