### PR TITLE
docs(readme): status badges for build, docs, license, etc. 

### LINKED ISSUE #306: docs(readme): status badges for build, docs, license, etc.
### Description
As a prospective user of Cactus I want to have instant and visual feedback on the project's baseline health metrics via badges so that I feel better about spending my time getting to know what Cactus is about, how it works and what/when/how could I contribute to the community.

See https://github.com/dwyl/repo-badges

### Acceptance Criteria
1. Badges are added on top of the readme file

cc: @jonathan-m-hamilton @sfuji822 @takeutak

### PR DESCRIPTION
**Pull request by beckettnormington**
Responding to issue #306 

If these need updating, let me know!

Fixes #306

Edit from Peter: Added the `Fixes #306` line which will auto-close the issue once this PR is merged.

### CODE REVIEW

**Comment by beckettnormington** [comment]
I'm not sure what happened with the checks.

**Comment by beckettnormington** [comment]
Going to fix DCO sign-off

**Comment by beckettnormington** [comment]
DCO Check Fixed

**Review by petermetz — APPROVED** [review]
LGTM

Thank you very much @beckettnormington !

cc: @takeutak @sfuji822

**Comment by beckettnormington** [comment]
You’re very welcome!

**Review by jonathan-m-hamilton — APPROVED** [review]
LGTM!  Thanks again @beckettnormington

**Pull request merged**
