### PR TITLE
feat(example): make cartrade support more environments

### PR DESCRIPTION
**Pull request by t-yasushi**
This PR resolves Issue #1512 .
Some environments (ex. not centos) have problems with fabcar operation, so I want to make cartrade applications available in more environments. To do this, I first introduce minifabric:<https://github.com/hyperledger-labs/minifabric>.

Signed-off-by: Yasushi Takahashi <t-yasushi@fujitsu.com>

### CODE REVIEW

**Comment by takeutak** [comment]
@t-yasushi Thanks for contributing! I'd like to ask your favor as the following:

- This PR is related with ledger tools so I'd like to move this file to cactus/tools directory (e.g. cactus/tools/docker/fabric-minifabric ?) Would you move this file?

**Comment by t-yasushi** [comment]
@takeutak 
Thank you for your comments! I made the directory named "fabric-minifabric" in tools/docker and moved "how_to_use_minifabric.md" to tools/docker/fabric-minifabric. 
Moreover, I find how to containerize fabcar, so I keep "how_to_containerize_fabcar.md" in tools/docker/fabcar14-fabcar-testnet.

**Review by petermetz — APPROVED** [review]
@t-yasushi LGTM

**Comment by jagpreetsinghsasan** [comment]
Hi @t-yasushi 
Any updates on this? (As it is still in draft)

**Comment by takeutak** [comment]
On behalf of @t-yasushi , we would like to close this draft pull-request because this draft is out-of-date.

**Pull request closed without merging**
