### PR TITLE
feat(core-api): add plugin object store interface definition

### PR DESCRIPTION
**Pull request by petermetz**
This will be implemented by object store plugins so as to
have guarantee that at runtime the plugins can be used the
way the caller expects them to.

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

### CODE REVIEW

**Comment by takeutak** [comment]
@petermetz Just to confirm, what is the intent behind the functionality around this IPFS plugin? (What data are you going to put on distributed storage?)  **related with #1007, #1033

**Comment by petermetz** [comment]
> @petermetz Just to confirm, what is the intent behind the functionality around this IPFS plugin? (What types of data are you going to put on distributed storage?) **related with #1007, #1033

@takeutak Nothing planned at the moment. It will be up to the BLP authors to use it as they see fit, store the kind of data they want as part of their business logic.

**Comment by takeutak** [comment]
@petermetz Thanks to answer! Is this IPFS function required by releasing V1-RC as the roadmap #716 ? If this is not so, I would like to arrange the core functions on the roadmap on #716 and I'm sure that we should concentrate on the development of core functions. (related with #1007, #1033)

**Comment by petermetz** [comment]
@takeutak Cheers! It's not needed for 1.0-RC, but it is needed for something else internally.

**Comment by takeutak** [comment]
@petermetz Thanks for your comment. Would you change the IPFS plugin to IPFS extension feature (an optional feature) since this is not a required one?

**Comment by takeutak** [comment]
@petermetz Thanks for your commit.
As I discussed on the previous, IPFS plugin seems to be suitable to be moved to an extension feature (= optional feature).
The features about ObjectRequest (GetObjectRequestV1, HasObjectRequestV1, etc.) seem to be ones for IPFS plugins. Could you mind if you move these features to some extension?

**Comment by petermetz** [comment]
> @petermetz Thanks for your commit.
> As I discussed on the previous, IPFS plugin seems to be suitable to be moved to an extension feature (= optional feature).
> The features about ObjectRequest (GetObjectRequestV1, HasObjectRequestV1, etc.) seem to be ones for IPFS plugins. Could you mind if you move these features to some extension?

@takeutak I would need to create a brand new package for it. Is that acceptable?

**Review by takeutak — APPROVED** [review]

**Review by kikoncuo — APPROVED** [review]

**Pull request merged**
