### PR TITLE
Integrate engine.io and upgrade socket.io to 3.0.0

### PR DESCRIPTION
**Pull request by bhaskarvilles**
engine.io is a realtime engine behind Socket.IO. It provides the foundation of a bidirectional connection between client and server

Affected versions of this package are vulnerable to Denial of Service (DoS) via a POST request to the long polling transport.

Commit sha: 4d3b1ac, Author: Bhaskara Ram, Committer: GitHub; Signed-off-by: Bhaskar Ram <bhaskar@parrotsec.in>

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@bhaskarvilles Thank you, LGTM

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by bhaskarvilles** [comment]
Merging in next release ?

**Comment by petermetz** [comment]
> Merging in next release ?

@bhaskarvilles Yeah it will be a part of the next release that's coming out for sure.

**Review by petermetz — CHANGES_REQUESTED** [review]
@bhaskarvilles Please make it so that the DCO check (and all the other checks) are passing (it's a legal requirement that we cannot ignore).
If you need help on how to do it, there are specific instructions if you click through the 'details' link of the failing check for the DCO.
If that doesn't help enough just let me know and I can provide more specific instructions here or on the chat/mailing list.

**Comment by bhaskarvilles** [comment]
@petermetz Done , Enabled DCO

**Comment by petermetz** [comment]
> @petermetz Done , Enabled DCO

@bhaskarvilles I see that you added a GPG signature to the commit which is great, but unfortunately that's not the one we are looking for (even though from a technical perspective it would make much more sense).
The sign-off is a separate feature in git which doesn't do anything cryptography related (like signing the commit does) instead it literally just puts a line at the bottom of the commit message stating that you signed off on it. Let me know if you need more help.

**Comment by bhaskarvilles** [comment]
Yes can you explain it for me ?

**Comment by petermetz** [comment]
> Yes can you explain it for me ?

@bhaskarvilles To put it short, you need to go to the 'details' link of the DCO check on the bottom of this page and there you'll see some git commands that you need to execute in order to add the sign-off after the fact. Then you need to do a force push with lease like `git push --force-with-lease` so that your remote branch gets the changes as well.

**Review by bhaskarvilles — COMMENTED** [review]
Signed-off-by: Bhaskar Ram <bhaskar@parrotsec.in>

**Comment by bhaskarvilles** [comment]
Added DCO to PR, can you merge it now ?

**Comment by bhaskarvilles** [comment]
> Added DCO to PR, can you merge it now ?

BTW I'm not using Github CLI now so, please don't mind my mistake in doing that.

**Comment by petermetz** [comment]
> Added DCO to PR, can you merge it now ?

@bhaskarvilles Sorry but it looks like you either haven't did the sign-off by accident or just forgot to force push. The commit still has no sign-off on the remote branch:

Screenshot from 2022-01-26 16-08-08

**Review by bhaskarvilles — COMMENTED** [review]
engine.io is a realtime engine behind Socket.IO. It provides the foundation of a bidirectional connection between client and server

Affected versions of this package are vulnerable to Denial of Service (DoS) via a POST request to the long polling transport.

Commit sha: 4d3b1ac, Author: Bhaskara Ram, Committer: GitHub; Signed-off-by: Bhaskar Ram <bhaskar@parrotsec.in>

**Comment by petermetz** [comment]
> engine.io is a realtime engine behind Socket.IO. It provides the foundation of a bidirectional connection between client and server
> 
> Affected versions of this package are vulnerable to Denial of Service (DoS) via a POST request to the long polling transport.
> 
> Commit sha: [4d3b1ac](https://github.com/hyperledger/cactus/commit/4d3b1ac8a0a0d17b2d2d91fbae23df5f7534d880), Author: Bhaskara Ram, Committer: GitHub; Signed-off-by: Bhaskar Ram [bhaskar@parrotsec.in](mailto:bhaskar@parrotsec.in)

@bhaskarvilles Still not passing the DCO/SPR checks unfortunately. Can you invite me as a collaborator to your fork and then maybe I can just fix it for you?

**Comment by bhaskarvilles** [comment]
> > engine.io is a realtime engine behind Socket.IO. It provides the foundation of a bidirectional connection between client and server
> > 
> > Affected versions of this package are vulnerable to Denial of Service (DoS) via a POST request to the long polling transport.
> > 
> > Commit sha: [4d3b1ac](https://github.com/hyperledger/cactus/commit/4d3b1ac8a0a0d17b2d2d91fbae23df5f7534d880), Author: Bhaskara Ram, Committer: GitHub; Signed-off-by: Bhaskar Ram [bhaskar@parrotsec.in](mailto:bhaskar@parrotsec.in)
> 
> @bhaskarvilles Still not passing the DCO/SPR checks unfortunately. Can you invite me as a collaborator to your fork and then maybe I can just fix it for you?

Invited for collaboration with you please check your email.

**Comment by bhaskarvilles** [comment]
@petermetz have you reviewed it ?

**Comment by petermetz** [comment]
@bhaskarvilles Very sorry but it looks like the Fujitsu maintainers have deleted their code in the meantime that you were trying to provide fixes for them. I apologize for the slow turnaround this was absolutely my fault that you could not get your contribution in on time. I'd be happy to help with any future contributions of course, we appreciate the help!

**Pull request closed without merging**
