### PR TITLE
test: jestify is-string test

### PR DESCRIPTION
**Pull request by awadhana**
Migrated test from Tap to Jest.

File Path:
packages/cactus-common/src/test/typescript/unit/strings/is-string.test.ts

This is a PARTIAL resolution to issue #238

Signed-off-by: awadhana <awadhana0825@gmail.com>

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@awadhana LGTM, thank you!

**Review by takeutak — APPROVED** [review]

**Comment by petermetz** [comment]
@awadhana Not sure yet what's going wrong on this one. I will restart the CI now and if it fails again (and the same way), then I think it warrants an investigation based on the logs because it consistently seems to fail here:

```sh
# Subtest: ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
    1..0 # no tests found
not ok 89 - ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts # time=6973.904ms
  ---
  env:
    TS_NODE_COMPILER_OPTIONS: "{}"
  file: ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
  timeout: 900000
  command: /opt/hostedtoolcache/node/14.17.6/x64/bin/node
  args:
    - -r
    - /home/runner/work/cactus/cactus/node_modules/ts-node/register/index.js
    - --max-old-space-size=4096
    - ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/runner/work/cactus/cactus
  exitCode: 1
  ...

Bail out! ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
```

**Comment by awadhana** [comment]
> @awadhana Not sure yet what's going wrong on this one. I will restart the CI now and if it fails again (and the same way), then I think it warrants an investigation based on the logs because it consistently seems to fail here:
> 
> ```shell
> # Subtest: ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
>     1..0 # no tests found
> not ok 89 - ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts # time=6973.904ms
>   ---
>   env:
>     TS_NODE_COMPILER_OPTIONS: "{}"
>   file: ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
>   timeout: 900000
>   command: /opt/hostedtoolcache/node/14.17.6/x64/bin/node
>   args:
>     - -r
>     - /home/runner/work/cactus/cactus/node_modules/ts-node/register/index.js
>     - --max-old-space-size=4096
>     - ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
>   stdio:
>     - 0
>     - pipe
>     - 2
>   cwd: /home/runner/work/cactus/cactus
>   exitCode: 1
>   ...
> 
> Bail out! ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
> ```

@petermetz  it looks like it's still failing, any updates?

**Comment by awadhana** [comment]
> @awadhana Not sure yet what's going wrong on this one. I will restart the CI now and if it fails again (and the same way), then I think it warrants an investigation based on the logs because it consistently seems to fail here:
> 
> ```shell
> # Subtest: ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
>     1..0 # no tests found
> not ok 89 - ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts # time=6973.904ms
>   ---
>   env:
>     TS_NODE_COMPILER_OPTIONS: "{}"
>   file: ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
>   timeout: 900000
>   command: /opt/hostedtoolcache/node/14.17.6/x64/bin/node
>   args:
>     - -r
>     - /home/runner/work/cactus/cactus/node_modules/ts-node/register/index.js
>     - --max-old-space-size=4096
>     - ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
>   stdio:
>     - 0
>     - pipe
>     - 2
>   cwd: /home/runner/work/cactus/cactus
>   exitCode: 1
>   ...
> 
> Bail out! ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
> ```

@petermetz  it looks like it's still failing, any updates?

**Comment by awadhana** [comment]
> @awadhana Not sure yet what's going wrong on this one. I will restart the CI now and if it fails again (and the same way), then I think it warrants an investigation based on the logs because it consistently seems to fail here:
> 
> ```shell
> # Subtest: ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
>     1..0 # no tests found
> not ok 89 - ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts # time=6973.904ms
>   ---
>   env:
>     TS_NODE_COMPILER_OPTIONS: "{}"
>   file: ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
>   timeout: 900000
>   command: /opt/hostedtoolcache/node/14.17.6/x64/bin/node
>   args:
>     - -r
>     - /home/runner/work/cactus/cactus/node_modules/ts-node/register/index.js
>     - --max-old-space-size=4096
>     - ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
>   stdio:
>     - 0
>     - pipe
>     - 2
>   cwd: /home/runner/work/cactus/cactus
>   exitCode: 1
>   ...
> 
> Bail out! ./packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
> ```

@petermetz, looks like the same error from another file. I've fixed it and pushed. Hopefully everything passes this time around

**Review by petermetz — CHANGES_REQUESTED** [review]
@awadhana Squash is still missing

**Comment by awadhana** [comment]
> @awadhana Squash is still missing

@petermetz hopefully solid now :)

**Review by petermetz — COMMENTED** [review]
@awadhana Looks good to me now, but I wanted to double check: is it intentional that now you have 3 tests migrated in the same PR? Wanted to make sure because it's fine by me, but if you have open PRs for the other two tests in parallel then those will need to be closed if we merge this in as-is (which I have no problem with either)

**Comment by awadhana** [comment]
> @awadhana Looks good to me now, but I wanted to double check: is it intentional that now you have 3 tests migrated in the same PR? Wanted to make sure because it's fine by me, but if you have open PRs for the other two tests in parallel then those will need to be closed if we merge this in as-is (which I have no problem with either)

@petermetz nope, that was not intended. I think something weird happened because it looks like this PR was merged sometime before and then the changes from main creeped up here, because those files have already been made into separate merged PR's so they looked like they were part of this branch? Not sure, but it's been fixed and pushed now so hopefully it's solid :)

**Review by petermetz — APPROVED** [review]
@awadhana Yup, looks legit, thank you!

**Pull request merged**
