### PR TITLE
feat(odap-plugin): odap crash recovery first implementation

### PR DESCRIPTION
**Pull request by AndreAugusto11**
* Addition of retries when making requests
* Addition of timeouts when making requests
* Addition of endpoints for recovery procedure
* Tests with crashes in the first phase of the protocol
* Addition of logging in local SQLite database
* IPFS is now only to store hashes and signatures of the logs and proofs/claims
* Migrate odap-api-call-with-ledger-connector.test from tape to jest
* Addition of rollbacks when counterparty gateway is and is not crashed
* Update README.md with a new protocol image and the description of each test file

### CODE REVIEW

**Comment by AndreAugusto11** [comment]
@petermetz unfortunately, none of the solutions we talked about seems to work

**Comment by AndreAugusto11** [comment]
@petermetz problem solved. I was missing the line `import "jest-extended"` in some tests. It was strangely causing all the other tests outside the package to have those missing property errors.

**Comment by AndreAugusto11** [comment]
cc @RafaelAPB

**Review by petermetz — APPROVED** [review]
> @petermetz problem solved. I was missing the line `import "jest-extended"` in some tests. It was strangely causing all the other tests outside the package to have those missing property errors.  

@AndreAugusto11 Ahh, that's an annoying one for sure. :-)

Glad you figured it out though! LGTM

**Comment by RafaelAPB** [comment]
LGTM. A lot of effort put into this for sure!

**Review by takeutak — APPROVED** [review]

**Pull request merged**
